# -*- coding: utf-8 -*-
PT_BR = {
"play":"COMEÇAR","playLv":"Fase {0}","replayLv":"Rejogar · Fase {0}","playLast":"Rejogar a fase final",
"shop":"Loja de doces","back":"◀ Voltar","cancel":"Cancelar","max":"MÁX",
"resetBtn":"Recomeçar da fase 1","resetQ":"Recomeçar da fase 1?",
"resetSub":"Seu progresso será apagado. Não dá para desfazer.","resetOk":"Sim, recomeçar",
"shopTitle":"Loja de doces","shopCoins":"{0} moedas de doce",
"shopHint":"Melhorias permanentes, ativas desde o início de cada partida. Travado numa fase? Volte, junte moedas e fique mais forte.",
"pauseMsg":"Pausado","resume":"▶ Continuar","toMenu":"Menu principal",
"next":"Próxima fase ▶","again":"Jogar de novo","saveShot":"Salvar card",
"clear":"CONCLUÍDO!","gameover":"GAME OVER",
"nmWin":"Concluído! {0} inimigos eliminados","nmClose":"Você chegou a {0}% — faltavam só {1}s para passar!","nmFar":"{0}% alcançado · {1} eliminados",
"coinGain":"+{0} moedas de doce","coinTotal":"({0} no total)",
"allClear":"TUDO CONCLUÍDO","stageOf":"Fase {0} / {1}","congrats":"Todas as fases concluídas!",
"allClearDesc":"Você venceu todas as {0} fases. Jogue de novo e busque um tempo melhor.","bossCount":"Chefe ×{0}",
"cardTitle":"NÍV.{0}! Escolha uma","evolve":"EVOLUÇÃO","newWeapon":"NOVA","lvTag":"Nív.{0}","upgradeTag":"MELHORIA",
"hudLv":"NÍV.{0}","hudKills":"Abates {0}","hudStage":"Fase {0} · {1} ({2})",
"hudGoo":"Gosma {0}%  DANO +{1}%","hudSpeed":"Velocidade ×{0}","killBoss":"DERROTE O CHEFE!",
"bossWarn":"⚠ {0} SE APROXIMA","superBossTag":"⚠️ MEGA CHEFE · ",
"hintMove":"Toque em qualquer lugar da tela e arraste para se mover","hintDash":"» no canto inferior esquerdo = avanço na sua direção (invencível)",
"hintHearts":"Se perder todos os corações, acabou — sobreviva desviando","hintChest":"Siga a seta — tem um baú lá",
"noTouch":"⚠ Nenhum evento de toque detectado",
"tShield":"O escudo bloqueou!","tShieldGain":"ESCUDO","tFreeze":"CONGELADO!","tRevive":"🕯️ Reviveu! Restam {0}",
"tAllMaxHeart":"Tudo no máximo → coração restaurado!","tAllMaxGem":"Tudo no máximo → chuva de gemas!",
"tNuke":"☢️ BOMBA! {0} inimigos varridos","tBossIn":"{0} apareceu!","tSuperBossIn":"⚠️ MEGA CHEFE: {0}!",
"w_bubble_n":"Pistola de bolhas pressurizada","w_bubble_d":"Tiros retos e rápidos · DANO {0}",
"w_graffiti_n":"Spray de grafite arco-íris","w_graffiti_d":"Tiro em cone · {0} projéteis · deixa gosma",
"w_yoyo_n":"Ioiô bumerangue luminoso","w_yoyo_d":"Arremesso orbital · atravessa todos",
"e_bubble_n":"Temporal de gosma neon","e_bubble_d":"Chuva de gosma na tela toda, deixa os inimigos lentos",
"e_graffiti_n":"Tapete de gosma arco-íris","e_graffiti_d":"A gosma espalhada se incendeia em cadeia sozinha",
"e_yoyo_n":"Ioiô buraco negro","e_yoyo_d":"Puxa inimigos e gemas para o centro e tritura",
"u_sticky_n":"Xarope grudento","u_sticky_d":"Inimigos atingidos ficam presos 2s, com metade da velocidade",
"u_sticky_d2":"Dura 3,5s e se espalha para inimigos próximos",
"u_chain_n":"Detonação em cadeia","u_chain_d":"30% de chance de incendiar a gosma sob um inimigo abatido",
"u_chain_d2":"Chance sobe para 60%, raio de explosão maior",
"u_mine_n":"Gosma corrosiva","u_mine_d":"Inimigos em cima da gosma sofrem dano contínuo","u_mine_d2":"Dano dobrado e a gosma dura mais",
"u_freeze_n":"Rolamento gelado","u_freeze_d":"Ao terminar um avanço, congela inimigos próximos por 1,6s",
"u_shield_n":"Escudo rosquinha","u_shield_d":"A cada 18s gera um escudo que bloqueia um golpe",
"u_shield_d2":"A cada 10s, acumulando até 2",
"u_frenzy_n":"Pirulito frenesi","u_frenzy_d":"A cada 25 abates, velocidade de ataque dobrada por 4s","u_frenzy_d2":"A cada 15 abates, por 5s",
"u_split_n":"Bala divisora","u_split_d":"25% de chance de um abate lançar 3 estilhaços","u_split_d2":"50% de chance, 5 estilhaços",
"u_rage_n":"Fúria de coração cheio","u_rage_d":"+45% de dano com os corações cheios (perde ao levar dano)",
"u_panic_n":"Pirulito de primeiros socorros","u_panic_d":"+75% de velocidade por 3s após levar dano, invencibilidade maior",
"u_greed_n":"Carnaval da ganância","u_greed_d":"Cada gema dá 1 XP a mais","u_greed_d2":"Mais 1 XP, e as gemas brilham maiores",
"u_cd_n":"Rolamento suave","u_cd_d":"Recarga do avanço -0,8s","u_cd_d2":"Mais -0,6s e distância maior",
"u_regen_n":"Regeneração de goma","u_regen_d":"Recupera um coração a cada 40s","u_regen_d2":"A cada 25s",
"u_rangeUp_n":"Luneta de doce","u_rangeUp_d":"O alcance da mira automática aumenta um nível — veja antes de atirar",
"u_rangeUp_d2":"Mais um nível, perto do limite da arma",
"m_hearts_n":"Guarda coração de doce","m_hearts_d":"Corações iniciais +{0} ({1} no total)",
"m_dmg_n":"Lâmina de glacê","m_dmg_d":"Dano inicial +{0}%",
"m_aspd_n":"Batedor rápido","m_aspd_d":"Velocidade de ataque inicial +{0}%",
"m_wep_n":"Arma favorita","m_wep_d":"Nível da arma principal +{0}",
"m_range_n":"Lente de longo alcance","m_range_d":"Alcance de ataque inicial +{0}",
"m_xp_n":"Afinidade com gemas","m_xp_d":"Ganho de XP +{0}%",
"m_pickup_n":"Ímã atrator","m_pickup_d":"Raio de coleta de gemas +{0}",
"m_dash_n":"Mestre do rolamento","m_dash_d":"Recarga do avanço -{0}s",
"m_revive_n":"Vela do renascimento","m_revive_d":"Reviver no local {0} vez(es) (por fase)",
"m_coin_n":"Caçador de moedas","m_coin_d":"Moedas de doce ganhas +{0}%",
"b1":"Papelada de hora extra","b2":"Mensagens não lidas","b3":"Despertador ladrão de almas",
"sb0":"O Colosso KPI","sb1":"Demônio da reunião de segunda","sb2":"Espectro da hora extra infinita",
"sb3":"Praga do visto e não respondido","sb4":"Asura da avaliação anual","sb5":"Senhor da caixa de entrada lotada",
"sb6":"Buraco negro da carga","sb7":"Espectro da transição","sb8":"O Juiz silencioso","sb9":"Julgamento KPI final",
"c_heart_n":"Doce coração","c_heart_go":"Um coração restaurado!","c_heart_full":"Corações cheios → chuva de gemas!",
"c_nuke_n":"Chuva de doces","c_nuke_go":"{0} projéteis apagados!",
"c_speed_n":"Doce relâmpago","c_speed_go":"Velocidade de ataque dobrada por 9s!",
"c_rain_n":"Doce arco-íris","c_rain_go":"Invencível por 7s!",
"c_gold_n":"Doce dourado","c_gold_go":"Chuva de gemas!",
"c_ice_n":"Doce gelado","c_ice_go":"{0} inimigos congelados!",
"c_fire_n":"Doce de fogo","c_fire_go":"Gosma incendiada!",
"c_power_n":"Doce de poder","c_power_go":"+40% de dano por 10s!",
"tier0":"Novato","tier1":"Pegando o jeito","tier2":"Habilidoso","tier3":"Desafio","tier4":"Inferno",
"tier5":"Abismo","tier6":"Pesadelo","tier7":"Purgatório","tier8":"Vazio","tier9":"Asura",
"tier10":"Submundo","tier11":"Apocalipse","tier12":"Divino","tier13":"Fim",
"lv1n":"Creche de gelatina","lv1d":"Aprenda a arrastar para se mover. Inimigos lentos, pouca vida, sem contra-ataque.",
"lv2n":"Campina de balas de goma","lv2d":"Os mesmos inimigos, só que mais. Pratique sair dos cercos com o avanço.",
"lv3n":"Parquinho neon","lv3d":"★ Chegam os coelhos: o dobro da velocidade das gosmas. Menos inimigos para você se adaptar.",
"lv4n":"Vila explosiva","lv4d":"Mais coelhos. Agora é preciso se mexer de verdade.",
"lv5n":"Fábrica de geleia grudenta","lv5d":"★ Chegam os drones: atiram de longe. Use a invencibilidade do avanço para atravessar os tiros.",
"lv6n":"Casa de doces sob fogo","lv6d":"Tiros mais densos, fase mais longa. Daqui em diante, gerencie seus corações a sério.",
"lv7n":"Mina de gomas explosivas","lv7d":"★ Chegam os bombardeiros: explodem de perto, mas também incendeiam a gosma. Três chefes.",
"lv8n":"Cidade doce desgovernada","lv8d":"Os quatro tipos de inimigos. Nada novo — pura execução.",
"lv9n":"Inferno de caramelo","lv9d":"Vida, velocidade e velocidade dos projéteis todas aumentadas.",
"lv10n":"Final de gelatina","lv10d":"Final do primeiro capítulo. ★ O mega chefe estreia, muito mais duro que qualquer chefe normal. (Outro, mais assustador, espera a cada 10 fases.)",
"genName":"{0} {1}","genBossName":"Chefe de {0}: {1}",
"genDescBoss":"★ Final do capítulo {0}: o mega chefe \"{1}\" segura a linha, mais forte que o capítulo anterior em tudo.",
"genDescOpener":"Entrando em \"{0}\". A pressão diminui depois do capítulo anterior — prepare-se para subir de novo.",
"genDescMid":"\"{0}\" mantém a pressão. A vida dos inimigos e a densidade de surgimento continuam subindo.",
"tFrenzy":"FRENESI! Velocidade de ataque dobrada","tMidBoss":"Baú dourado de sobrecarga! Um coração restaurado",
}
RU = {
"play":"НАЧАТЬ ИГРУ","playLv":"Уровень {0}","replayLv":"Заново · Уровень {0}","playLast":"Переиграть финал",
"shop":"Магазин сладостей","back":"◀ Назад","cancel":"Отмена","max":"МАКС",
"resetBtn":"Начать с 1-го уровня","resetQ":"Начать заново с 1-го уровня?",
"resetSub":"Весь прогресс будет удалён. Это действие необратимо.","resetOk":"Да, начать заново",
"shopTitle":"Магазин сладостей","shopCoins":"{0} конфетных монет",
"shopHint":"Постоянные улучшения, действуют с начала каждого забега. Застряли на уровне? Вернитесь, накопите монеты и станьте сильнее.",
"pauseMsg":"Пауза","resume":"▶ Продолжить","toMenu":"Главное меню",
"next":"Следующий уровень ▶","again":"Играть снова","saveShot":"Сохранить карточку",
"clear":"ПРОЙДЕНО!","gameover":"GAME OVER",
"nmWin":"Пройдено! Убито {0}","nmClose":"Вы дошли до {0}% — оставалось всего {1} с!","nmFar":"Достигнуто {0}% · убито {1}",
"coinGain":"+{0} конфетных монет","coinTotal":"(всего {0})",
"allClear":"ВСЁ ПРОЙДЕНО","stageOf":"Уровень {0} / {1}","congrats":"Все уровни пройдены!",
"allClearDesc":"Вы прошли все {0} уровней. Сыграйте снова и улучшите время.","bossCount":"Боссы ×{0}",
"cardTitle":"УР.{0}! Выберите одну","evolve":"ЭВОЛЮЦИЯ","newWeapon":"НОВОЕ","lvTag":"Ур.{0}","upgradeTag":"УЛУЧШЕНИЕ",
"hudLv":"УР.{0}","hudKills":"Убито {0}","hudStage":"Уровень {0} · {1} ({2})",
"hudGoo":"Слизь {0}%  УРОН +{1}%","hudSpeed":"Скорость ×{0}","killBoss":"УБЕЙТЕ БОССА!",
"bossWarn":"⚠ {0} ПРИБЛИЖАЕТСЯ","superBossTag":"⚠️ МЕГАБОСС · ",
"hintMove":"Коснитесь экрана в любом месте и тяните, чтобы двигаться","hintDash":"» внизу слева = рывок в сторону движения (неуязвимость)",
"hintHearts":"Кончились сердца — конец. Выживайте, уклоняясь","hintChest":"Идите за стрелкой — там сундук",
"noTouch":"⚠ Касания не обнаружены",
"tShield":"Щит заблокировал!","tShieldGain":"ЩИТ","tFreeze":"ЗАМОРОЖЕНО!","tRevive":"🕯️ Возрождение! Осталось {0}",
"tAllMaxHeart":"Всё на максимуме → сердце восстановлено!","tAllMaxGem":"Всё на максимуме → дождь кристаллов!",
"tNuke":"☢️ ВЗРЫВ! Уничтожено {0} врагов","tBossIn":"{0} появляется!","tSuperBossIn":"⚠️ МЕГАБОСС: {0}!",
"w_bubble_n":"Пузырьковый водомёт","w_bubble_d":"Быстрые прямые выстрелы · УРОН {0}",
"w_graffiti_n":"Радужный баллончик","w_graffiti_d":"Веерный выстрел · {0} снарядов · оставляет слизь",
"w_yoyo_n":"Светящееся йо-йо-бумеранг","w_yoyo_d":"Круговой бросок · пробивает всех",
"e_bubble_n":"Неоновый слизневый ливень","e_bubble_d":"Дождь из слизи на весь экран, замедляет врагов",
"e_graffiti_n":"Радужный слизневый ковёр","e_graffiti_d":"Разбрызганная слизь сама воспламеняется цепью",
"e_yoyo_n":"Гравитационное йо-йо","e_yoyo_d":"Втягивает врагов и кристаллы к центру и перемалывает",
"u_sticky_n":"Липкий сироп","u_sticky_d":"Задетые враги прилипают на 2 с, скорость вдвое ниже",
"u_sticky_d2":"Длится 3,5 с и передаётся соседним врагам",
"u_chain_n":"Цепная детонация","u_chain_d":"30% шанс поджечь слизь под убитым врагом",
"u_chain_d2":"Шанс до 60%, радиус взрыва больше",
"u_mine_n":"Едкая слизь","u_mine_d":"Враги в слизи получают урон со временем","u_mine_d2":"Двойной урон, слизь держится дольше",
"u_freeze_n":"Ледяной перекат","u_freeze_d":"В конце рывка замораживает врагов рядом на 1,6 с",
"u_shield_n":"Щит-пончик","u_shield_d":"Каждые 18 с появляется щит, блокирующий один удар",
"u_shield_d2":"Каждые 10 с, до 2 зарядов",
"u_frenzy_n":"Леденец ярости","u_frenzy_d":"Каждые 25 убийств — двойная скорость атаки на 4 с","u_frenzy_d2":"Каждые 15 убийств, на 5 с",
"u_split_n":"Делящийся мармелад","u_split_d":"25% шанс выпустить 3 осколка при убийстве","u_split_d2":"Шанс 50%, 5 осколков",
"u_rage_n":"Ярость полного сердца","u_rage_d":"+45% урона при полных сердцах (теряется при попадании)",
"u_panic_n":"Аптечка-леденец","u_panic_d":"+75% скорости на 3 с после удара, неуязвимость дольше",
"u_greed_n":"Карнавал жадности","u_greed_d":"Каждый кристалл даёт +1 опыта","u_greed_d2":"Ещё +1 опыта, кристаллы светятся ярче",
"u_cd_n":"Плавный перекат","u_cd_d":"Перезарядка рывка -0,8 с","u_cd_d2":"Ещё -0,6 с и дальность рывка больше",
"u_regen_n":"Мармеладная регенерация","u_regen_d":"Одно сердце каждые 40 с","u_regen_d2":"Каждые 25 с",
"u_rangeUp_n":"Конфетная подзорная труба","u_rangeUp_d":"Радиус автоприцела шире на ступень — увидьте их до выстрела",
"u_rangeUp_d2":"Ещё ступень, близко к пределу оружия",
"m_hearts_n":"Защита конфетного сердца","m_hearts_d":"Стартовые сердца +{0} (всего {1})",
"m_dmg_n":"Глазурный клинок","m_dmg_d":"Стартовый урон +{0}%",
"m_aspd_n":"Быстрый венчик","m_aspd_d":"Стартовая скорость атаки +{0}%",
"m_wep_n":"Любимое оружие","m_wep_d":"Уровень основного оружия +{0}",
"m_range_n":"Дальнозоркая линза","m_range_d":"Стартовая дальность атаки +{0}",
"m_xp_n":"Сродство с кристаллами","m_xp_d":"Получение опыта +{0}%",
"m_pickup_n":"Притягивающий магнит","m_pickup_d":"Радиус сбора кристаллов +{0}",
"m_dash_n":"Мастер переката","m_dash_d":"Перезарядка рывка -{0} с",
"m_revive_n":"Свеча возрождения","m_revive_d":"Возрождение на месте {0} раз (за уровень)",
"m_coin_n":"Охотник за монетами","m_coin_d":"Конфетных монет за забег +{0}%",
"b1":"Сверхурочные бумаги","b2":"Непрочитанные сообщения","b3":"Будильник-душелов",
"sb0":"Колосс KPI","sb1":"Демон понедельничной планёрки","sb2":"Призрак бесконечных переработок",
"sb3":"Бич прочитанного-без-ответа","sb4":"Асура годовой аттестации","sb5":"Владыка переполненной почты",
"sb6":"Чёрная дыра нагрузки","sb7":"Выходец передачи дел","sb8":"Молчаливый Судья","sb9":"Финальный суд KPI",
"c_heart_n":"Конфета-сердце","c_heart_go":"Одно сердце восстановлено!","c_heart_full":"Сердца полны → дождь кристаллов!",
"c_nuke_n":"Конфетный дождь","c_nuke_go":"Стёрто снарядов: {0}!",
"c_speed_n":"Молниеносная конфета","c_speed_go":"Двойная скорость атаки на 9 с!",
"c_rain_n":"Радужная конфета","c_rain_go":"Неуязвимость 7 с!",
"c_gold_n":"Монетная конфета","c_gold_go":"Дождь кристаллов!",
"c_ice_n":"Ледяная конфета","c_ice_go":"Заморожено врагов: {0}!",
"c_fire_n":"Огненная конфета","c_fire_go":"Слизь воспламенена!",
"c_power_n":"Конфета силы","c_power_go":"+40% урона на 10 с!",
"tier0":"Новичок","tier1":"Освоение","tier2":"Умелый","tier3":"Испытание","tier4":"Пекло",
"tier5":"Бездна","tier6":"Кошмар","tier7":"Чистилище","tier8":"Пустота","tier9":"Асура",
"tier10":"Преисподняя","tier11":"Апокалипсис","tier12":"Божественное","tier13":"Финал",
"lv1n":"Желейный детский сад","lv1d":"Научитесь двигаться перетаскиванием. Враги медленные, слабые и не отвечают.",
"lv2n":"Мармеладный луг","lv2d":"Те же враги, только больше. Потренируйтесь выходить из окружения рывком.",
"lv3n":"Неоновая площадка","lv3d":"★ Появляются кролики: вдвое быстрее слизней. Врагов меньше, чтобы вы привыкли.",
"lv4n":"Городок шипучки","lv4d":"Кроликов больше. Теперь двигаться придётся по-настоящему.",
"lv5n":"Фабрика липкого джема","lv5d":"★ Появляются дроны: стреляют издалека. Проходите сквозь пули на неуязвимости рывка.",
"lv6n":"Конфетный дом под обстрелом","lv6d":"Пуль больше, уровень длиннее. С этого момента следите за сердцами всерьёз.",
"lv7n":"Шахта взрывного мармелада","lv7d":"★ Появляются камикадзе: взрываются вблизи, но поджигают слизь. Три босса.",
"lv8n":"Взбесившийся конфетный город","lv8d":"Все четыре типа врагов. Ничего нового — чистое мастерство.",
"lv9n":"Карамельное пекло","lv9d":"Здоровье, скорость и скорость пуль — всё повышено.",
"lv10n":"Желейный финал","lv10d":"Финал первой главы. ★ Дебютирует мегабосс, куда крепче любого обычного босса. (Каждые 10 уровней ждёт ещё страшнее.)",
"genName":"{0} {1}","genBossName":"Босс главы «{0}»: {1}",
"genDescBoss":"★ Финал главы {0}: мегабосс «{1}» держит оборону, во всём сильнее прошлой главы.",
"genDescOpener":"Вход в «{0}». После прошлой главы давление ненадолго спадает — готовьтесь снова подниматься.",
"genDescMid":"«{0}» продолжает давить. Здоровье врагов и плотность появления растут.",
"tFrenzy":"ЯРОСТЬ! Двойная скорость атаки","tMidBoss":"Золотой сундук перегрузки! Одно сердце восстановлено",
}
