# -*- coding: utf-8 -*-
ES = {
"play":"EMPEZAR","playLv":"Nivel {0}","replayLv":"Repetir · Nivel {0}","playLast":"Repetir nivel final",
"shop":"Tienda de dulces","back":"◀ Volver","cancel":"Cancelar","max":"MÁX",
"resetBtn":"Reiniciar desde el nivel 1","resetQ":"¿Reiniciar desde el nivel 1?",
"resetSub":"Tu progreso se borrará. Esta acción no se puede deshacer.","resetOk":"Sí, reiniciar",
"shopTitle":"Tienda de dulces","shopCoins":"{0} monedas de caramelo",
"shopHint":"Mejoras permanentes, activas desde el inicio de cada partida. ¿Atascado en un nivel? Vuelve, consigue monedas y hazte más fuerte.",
"pauseMsg":"En pausa","resume":"▶ Continuar","toMenu":"Menú principal",
"next":"Siguiente nivel ▶","again":"Jugar otra vez","saveShot":"Guardar tarjeta",
"clear":"¡SUPERADO!","gameover":"GAME OVER",
"nmWin":"¡Superado! {0} enemigos eliminados","nmClose":"Llegaste al {0}% — ¡solo {1}s más para superarlo!","nmFar":"{0}% alcanzado · {1} eliminados",
"coinGain":"+{0} monedas de caramelo","coinTotal":"({0} en total)",
"allClear":"TODO SUPERADO","stageOf":"Nivel {0} / {1}","congrats":"¡Todos los niveles superados!",
"allClearDesc":"Has superado los {0} niveles. Juega otra vez y busca un tiempo mejor.","bossCount":"Jefe ×{0}",
"cardTitle":"¡NIV.{0}! Elige una","evolve":"EVOLUCIÓN","newWeapon":"NUEVA","lvTag":"Niv.{0}","upgradeTag":"MEJORA",
"hudLv":"NIV.{0}","hudKills":"Bajas {0}","hudStage":"Nivel {0} · {1} ({2})",
"hudGoo":"Gelatina {0}%  DAÑO +{1}%","hudSpeed":"Velocidad ×{0}","killBoss":"¡DERROTA AL JEFE!",
"bossWarn":"⚠ {0} SE ACERCA","superBossTag":"⚠️ MEGAJEFE · ",
"hintMove":"Toca cualquier parte de la pantalla y arrastra para moverte","hintDash":"» abajo a la izquierda = impulso en tu dirección (invulnerable)",
"hintHearts":"Si pierdes todos los corazones, se acabó — sobrevive esquivando","hintChest":"Sigue la flecha — allí hay un cofre",
"noTouch":"⚠ No se detectan eventos táctiles",
"tShield":"¡El escudo lo bloqueó!","tShieldGain":"ESCUDO","tFreeze":"¡CONGELADO!","tRevive":"🕯️ ¡Revivido! Quedan {0}",
"tAllMaxHeart":"Todo al máximo → ¡corazón restaurado!","tAllMaxGem":"Todo al máximo → ¡lluvia de gemas!",
"tNuke":"☢️ ¡BOMBA! {0} enemigos eliminados","tBossIn":"¡Aparece {0}!","tSuperBossIn":"⚠️ MEGAJEFE: ¡{0}!",
"w_bubble_n":"Pistola de burbujas a presión","w_bubble_d":"Disparos rectos rápidos · DAÑO {0}",
"w_graffiti_n":"Espray de grafiti arcoíris","w_graffiti_d":"Disparo en cono · {0} proyectiles · deja gelatina",
"w_yoyo_n":"Yoyó bumerán luminoso","w_yoyo_d":"Lanzamiento orbital · atraviesa a todos",
"e_bubble_n":"Aguacero de gelatina neón","e_bubble_d":"Lluvia de gelatina en toda la pantalla, ralentiza a los enemigos",
"e_graffiti_n":"Alfombra de gelatina arcoíris","e_graffiti_d":"La gelatina rociada se enciende en cadena sola",
"e_yoyo_n":"Yoyó agujero negro","e_yoyo_d":"Atrae enemigos y gemas al centro y los tritura",
"u_sticky_n":"Jarabe pegajoso","u_sticky_d":"Los enemigos golpeados quedan pegados 2s, a mitad de velocidad",
"u_sticky_d2":"Dura 3,5s y se contagia a los enemigos cercanos",
"u_chain_n":"Detonación en cadena","u_chain_d":"30% de probabilidad de encender la gelatina bajo un enemigo eliminado",
"u_chain_d2":"Probabilidad al 60%, mayor radio de explosión",
"u_mine_n":"Gelatina corrosiva","u_mine_d":"Los enemigos sobre la gelatina reciben daño continuo","u_mine_d2":"Daño doble y la gelatina dura más",
"u_freeze_n":"Rodada de hielo","u_freeze_d":"Al terminar un impulso, congela a los enemigos cercanos 1,6s",
"u_shield_n":"Escudo dónut","u_shield_d":"Cada 18s genera un escudo que bloquea un golpe",
"u_shield_d2":"Cada 10s en su lugar, hasta 2 acumulables",
"u_frenzy_n":"Piruleta frenesí","u_frenzy_d":"Cada 25 bajas, doble velocidad de ataque 4s","u_frenzy_d2":"Cada 15 bajas, durante 5s",
"u_split_n":"Gominola divisoria","u_split_d":"25% de probabilidad de lanzar 3 fragmentos al matar","u_split_d2":"50% de probabilidad, 5 fragmentos",
"u_rage_n":"Furia a corazón lleno","u_rage_d":"+45% de daño con los corazones llenos (se pierde al recibir un golpe)",
"u_panic_n":"Piruleta de primeros auxilios","u_panic_d":"+75% de velocidad durante 3s tras un golpe, más invulnerabilidad",
"u_greed_n":"Carnaval de la codicia","u_greed_d":"Cada gema da 1 EXP extra","u_greed_d2":"1 EXP más, y las gemas brillan más grandes",
"u_cd_n":"Rodada fluida","u_cd_d":"Recarga del impulso -0,8s","u_cd_d2":"-0,6s más, y mayor distancia de impulso",
"u_regen_n":"Regeneración gomosa","u_regen_d":"Recupera un corazón cada 40s","u_regen_d2":"Cada 25s en su lugar",
"u_rangeUp_n":"Catalejo de caramelo","u_rangeUp_d":"El alcance de puntería automática se amplía un nivel — velos antes de disparar",
"u_rangeUp_d2":"Un nivel más, cerca del límite del arma",
"m_hearts_n":"Guarda corazón de caramelo","m_hearts_d":"Corazones iniciales +{0} ({1} en total)",
"m_dmg_n":"Hoja de glaseado","m_dmg_d":"Daño inicial +{0}%",
"m_aspd_n":"Batidor rápido","m_aspd_d":"Velocidad de ataque inicial +{0}%",
"m_wep_n":"Arma favorita","m_wep_d":"Nivel del arma principal +{0}",
"m_range_n":"Lente de largo alcance","m_range_d":"Alcance de ataque inicial +{0}",
"m_xp_n":"Afinidad con gemas","m_xp_d":"Ganancia de EXP +{0}%",
"m_pickup_n":"Imán atrayente","m_pickup_d":"Radio de recogida de gemas +{0}",
"m_dash_n":"Maestro de la rodada","m_dash_d":"Recarga del impulso -{0}s",
"m_revive_n":"Vela de renacimiento","m_revive_d":"Revivir en el sitio {0} vez/veces (por nivel)",
"m_coin_n":"Cazador de monedas","m_coin_d":"Monedas de caramelo ganadas +{0}%",
"b1":"Papeleo de horas extra","b2":"Mensajes sin leer","b3":"Despertador robaalmas",
"sb0":"El Coloso KPI","sb1":"Demonio de la reunión del lunes","sb2":"Espectro de las horas extra infinitas",
"sb3":"Azote del mensaje ignorado","sb4":"Asura de la evaluación anual","sb5":"Señor del buzón desbordado",
"sb6":"Agujero negro de la carga","sb7":"Aparecido del traspaso","sb8":"El Juez silencioso","sb9":"Juicio KPI final",
"c_heart_n":"Caramelo corazón","c_heart_go":"¡Un corazón restaurado!","c_heart_full":"Corazones llenos → ¡lluvia de gemas!",
"c_nuke_n":"Lluvia de caramelos","c_nuke_go":"¡{0} proyectiles borrados!",
"c_speed_n":"Caramelo relámpago","c_speed_go":"¡Doble velocidad de ataque 9s!",
"c_rain_n":"Caramelo arcoíris","c_rain_go":"¡Invulnerable 7s!",
"c_gold_n":"Caramelo dorado","c_gold_go":"¡Lluvia de gemas!",
"c_ice_n":"Caramelo helado","c_ice_go":"¡{0} enemigos congelados!",
"c_fire_n":"Caramelo de fuego","c_fire_go":"¡Gelatina encendida!",
"c_power_n":"Caramelo de poder","c_power_go":"¡+40% de daño durante 10s!",
"tier0":"Novato","tier1":"Cogiendo el truco","tier2":"Hábil","tier3":"Desafío","tier4":"Infierno",
"tier5":"Abismo","tier6":"Pesadilla","tier7":"Purgatorio","tier8":"Vacío","tier9":"Asura",
"tier10":"Inframundo","tier11":"Apocalipsis","tier12":"Divino","tier13":"Final",
"lv1n":"Guardería de gelatina","lv1d":"Aprende a arrastrar para moverte. Enemigos lentos, poca vida, sin contraataque.",
"lv2n":"Pradera de gominolas","lv2d":"Los mismos enemigos, solo que más. Practica salir de los cercos con el impulso.",
"lv3n":"Parque de neón","lv3d":"★ Llegan los conejos: el doble de rápidos que los limos. Menos enemigos para que te adaptes.",
"lv4n":"Villa peta-zetas","lv4d":"Más conejos. Ahora sí que hay que moverse.",
"lv5n":"Fábrica de mermelada pegajosa","lv5d":"★ Llegan los drones: disparan a distancia. Usa la invulnerabilidad del impulso para cruzar los disparos.",
"lv6n":"Casa de caramelo acribillada","lv6d":"Disparos más densos, nivel más largo. Desde aquí gestiona tus corazones en serio.",
"lv7n":"Mina de gominolas explosivas","lv7d":"★ Llegan los kamikazes: explotan de cerca, pero también encienden la gelatina. Tres jefes.",
"lv8n":"Ciudad caramelo desbocada","lv8d":"Los cuatro tipos de enemigos. Nada nuevo — pura ejecución.",
"lv9n":"Infierno de caramelo","lv9d":"Vida, velocidad y velocidad de proyectiles todas al alza.",
"lv10n":"Final de gelatina","lv10d":"Final del primer capítulo. ★ Debuta el megajefe, mucho más duro que cualquier jefe normal. (Otro más aterrador espera cada 10 niveles.)",
"genName":"{0} {1}","genBossName":"Jefe de {0}: {1}",
"genDescBoss":"★ Final del capítulo {0}: el megajefe «{1}» aguanta la línea, más fuerte que el capítulo anterior en todo.",
"genDescOpener":"Entrando en «{0}». La presión baja tras el capítulo anterior — prepárate para volver a subir.",
"genDescMid":"«{0}» mantiene la presión. La vida de los enemigos y la densidad de aparición siguen subiendo.",
"tFrenzy":"¡FRENESÍ! Doble velocidad de ataque","tMidBoss":"¡Cofre dorado de sobrecarga! Un corazón restaurado",
}
IT = {
"play":"INIZIA","playLv":"Livello {0}","replayLv":"Rigioca · Livello {0}","playLast":"Rigioca l'ultimo livello",
"shop":"Negozio di caramelle","back":"◀ Indietro","cancel":"Annulla","max":"MAX",
"resetBtn":"Ricomincia dal livello 1","resetQ":"Ricominciare dal livello 1?",
"resetSub":"I tuoi progressi verranno cancellati. L'operazione è irreversibile.","resetOk":"Sì, ricomincia",
"shopTitle":"Negozio di caramelle","shopCoins":"{0} monete caramella",
"shopHint":"Potenziamenti permanenti, attivi dall'inizio di ogni partita. Bloccato su un livello? Torna, guadagna monete e diventa più forte.",
"pauseMsg":"In pausa","resume":"▶ Riprendi","toMenu":"Menu principale",
"next":"Livello successivo ▶","again":"Gioca di nuovo","saveShot":"Salva scheda",
"clear":"COMPLETATO!","gameover":"GAME OVER",
"nmWin":"Completato! {0} nemici eliminati","nmClose":"Sei arrivato al {0}% — ancora {1}s e ce la facevi!","nmFar":"{0}% raggiunto · {1} eliminati",
"coinGain":"+{0} monete caramella","coinTotal":"({0} in totale)",
"allClear":"TUTTO COMPLETATO","stageOf":"Livello {0} / {1}","congrats":"Tutti i livelli completati!",
"allClearDesc":"Hai superato tutti i {0} livelli. Rigioca e punta a un tempo migliore.","bossCount":"Boss ×{0}",
"cardTitle":"LIV.{0}! Scegline una","evolve":"EVOLUZIONE","newWeapon":"NUOVA","lvTag":"Liv.{0}","upgradeTag":"POTENZIATO",
"hudLv":"LIV.{0}","hudKills":"Uccisioni {0}","hudStage":"Livello {0} · {1} ({2})",
"hudGoo":"Gelatina {0}%  DANNO +{1}%","hudSpeed":"Velocità ×{0}","killBoss":"ABBATTI IL BOSS!",
"bossWarn":"⚠ {0} IN ARRIVO","superBossTag":"⚠️ MEGA BOSS · ",
"hintMove":"Tocca lo schermo ovunque e trascina per muoverti","hintDash":"» in basso a sinistra = scatto nella tua direzione (invulnerabile)",
"hintHearts":"Se finisci i cuori è finita — sopravvivi schivando","hintChest":"Segui la freccia — lì c'è uno scrigno",
"noTouch":"⚠ Nessun evento touch rilevato",
"tShield":"Lo scudo ha bloccato!","tShieldGain":"SCUDO","tFreeze":"CONGELATO!","tRevive":"🕯️ Rianimato! Ne restano {0}",
"tAllMaxHeart":"Tutto al massimo → cuore ripristinato!","tAllMaxGem":"Tutto al massimo → pioggia di gemme!",
"tNuke":"☢️ BOMBA! {0} nemici spazzati via","tBossIn":"{0} appare!","tSuperBossIn":"⚠️ MEGA BOSS: {0}!",
"w_bubble_n":"Pistola a bolle pressurizzata","w_bubble_d":"Colpi rapidi in linea · DANNO {0}",
"w_graffiti_n":"Spray graffiti arcobaleno","w_graffiti_d":"Colpo a cono · {0} proiettili · lascia gelatina",
"w_yoyo_n":"Yo-yo boomerang luminoso","w_yoyo_d":"Lancio orbitante · trapassa tutti",
"e_bubble_n":"Diluvio di gelatina neon","e_bubble_d":"Pioggia di gelatina su tutto lo schermo, rallenta i nemici",
"e_graffiti_n":"Tappeto di gelatina arcobaleno","e_graffiti_d":"La gelatina spruzzata si incendia a catena da sola",
"e_yoyo_n":"Yo-yo buco nero","e_yoyo_d":"Attira nemici e gemme al centro e li stritola",
"u_sticky_n":"Sciroppo appiccicoso","u_sticky_d":"I nemici colpiti restano bloccati 2s, a metà velocità",
"u_sticky_d2":"Dura 3,5s e si propaga ai nemici vicini",
"u_chain_n":"Detonazione a catena","u_chain_d":"30% di probabilità di incendiare la gelatina sotto un nemico ucciso",
"u_chain_d2":"Probabilità al 60%, raggio d'esplosione maggiore",
"u_mine_n":"Gelatina corrosiva","u_mine_d":"I nemici sulla gelatina subiscono danno nel tempo","u_mine_d2":"Danno raddoppiato e gelatina più duratura",
"u_freeze_n":"Rotolata di ghiaccio","u_freeze_d":"Alla fine di uno scatto, congela i nemici vicini per 1,6s",
"u_shield_n":"Scudo ciambella","u_shield_d":"Ogni 18s genera uno scudo che blocca un colpo",
"u_shield_d2":"Ogni 10s invece, fino a 2 cumulabili",
"u_frenzy_n":"Lecca-lecca frenesia","u_frenzy_d":"Ogni 25 uccisioni, velocità d'attacco doppia per 4s","u_frenzy_d2":"Ogni 15 uccisioni, per 5s",
"u_split_n":"Caramella divisoria","u_split_d":"25% di probabilità che un'uccisione spari 3 schegge","u_split_d2":"50% di probabilità, 5 schegge",
"u_rage_n":"Furia a cuori pieni","u_rage_d":"+45% danno con i cuori pieni (si perde al primo colpo)",
"u_panic_n":"Lecca-lecca di pronto soccorso","u_panic_d":"+75% velocità per 3s dopo un colpo, invulnerabilità più lunga",
"u_greed_n":"Carnevale dell'avidità","u_greed_d":"Ogni gemma dà 1 PE in più","u_greed_d2":"Ancora 1 PE, e le gemme brillano più grandi",
"u_cd_n":"Rotolata fluida","u_cd_d":"Ricarica scatto -0,8s","u_cd_d2":"Altri -0,6s e scatto più lungo",
"u_regen_n":"Rigenerazione gommosa","u_regen_d":"Recupera un cuore ogni 40s","u_regen_d2":"Ogni 25s invece",
"u_rangeUp_n":"Cannocchiale di zucchero","u_rangeUp_d":"La mira automatica si allarga di un livello — vedili prima di sparare",
"u_rangeUp_d2":"Un livello in più, vicino al limite dell'arma",
"m_hearts_n":"Guardia cuore di caramella","m_hearts_d":"Cuori iniziali +{0} ({1} in totale)",
"m_dmg_n":"Lama di glassa","m_dmg_d":"Danno iniziale +{0}%",
"m_aspd_n":"Frusta rapida","m_aspd_d":"Velocità d'attacco iniziale +{0}%",
"m_wep_n":"Arma preferita","m_wep_d":"Livello arma principale +{0}",
"m_range_n":"Lente a lunga gittata","m_range_d":"Gittata d'attacco iniziale +{0}",
"m_xp_n":"Affinità con le gemme","m_xp_d":"PE guadagnati +{0}%",
"m_pickup_n":"Magnete attrattore","m_pickup_d":"Raggio di raccolta gemme +{0}",
"m_dash_n":"Maestro di rotolata","m_dash_d":"Ricarica scatto -{0}s",
"m_revive_n":"Candela della rinascita","m_revive_d":"Rianimazione sul posto {0} volta/e (per livello)",
"m_coin_n":"Cacciatore di monete","m_coin_d":"Monete caramella guadagnate +{0}%",
"b1":"Scartoffie di straordinari","b2":"Messaggi non letti","b3":"Sveglia ruba-anime",
"sb0":"Il Colosso KPI","sb1":"Demone della riunione del lunedì","sb2":"Spettro degli straordinari infiniti",
"sb3":"Flagello del messaggio ignorato","sb4":"Asura della valutazione annuale","sb5":"Signore della casella piena",
"sb6":"Buco nero del carico","sb7":"Revenant del passaggio di consegne","sb8":"Il Giudice silenzioso","sb9":"Giudizio KPI finale",
"c_heart_n":"Caramella cuore","c_heart_go":"Un cuore ripristinato!","c_heart_full":"Cuori pieni → pioggia di gemme!",
"c_nuke_n":"Pioggia di caramelle","c_nuke_go":"{0} proiettili cancellati!",
"c_speed_n":"Caramella fulmine","c_speed_go":"Velocità d'attacco doppia per 9s!",
"c_rain_n":"Caramella arcobaleno","c_rain_go":"Invulnerabile per 7s!",
"c_gold_n":"Caramella dorata","c_gold_go":"Pioggia di gemme!",
"c_ice_n":"Caramella ghiacciata","c_ice_go":"{0} nemici congelati!",
"c_fire_n":"Caramella di fuoco","c_fire_go":"Gelatina incendiata!",
"c_power_n":"Caramella potenza","c_power_go":"+40% danno per 10s!",
"tier0":"Principiante","tier1":"Ci siamo","tier2":"Esperto","tier3":"Sfida","tier4":"Inferno",
"tier5":"Abisso","tier6":"Incubo","tier7":"Purgatorio","tier8":"Vuoto","tier9":"Asura",
"tier10":"Oltretomba","tier11":"Apocalisse","tier12":"Divino","tier13":"Epilogo",
"lv1n":"Asilo di gelatina","lv1d":"Impara a trascinare per muoverti. Nemici lenti, poca vita, nessun contrattacco.",
"lv2n":"Prateria di caramelle gommose","lv2d":"Gli stessi nemici, solo più numerosi. Allenati a uscire dagli accerchiamenti con lo scatto.",
"lv3n":"Parco giochi al neon","lv3d":"★ Arrivano i conigli: il doppio più veloci delle melme. Meno nemici per farti adattare.",
"lv4n":"Città frizzante","lv4d":"Più conigli. Ora bisogna muoversi davvero.",
"lv5n":"Fabbrica di marmellata appiccicosa","lv5d":"★ Arrivano i droni: sparano da lontano. Usa l'invulnerabilità dello scatto per attraversare i colpi.",
"lv6n":"Casa di caramelle crivellata","lv6d":"Colpi più fitti, livello più lungo. Da qui gestisci i cuori sul serio.",
"lv7n":"Miniera di gommose esplosive","lv7d":"★ Arrivano i kamikaze: esplodono da vicino, ma incendiano anche la gelatina. Tre boss.",
"lv8n":"Città caramella impazzita","lv8d":"Tutti e quattro i tipi di nemici. Niente di nuovo — pura esecuzione.",
"lv9n":"Inferno di caramello","lv9d":"Vita, velocità e velocità dei proiettili tutte aumentate.",
"lv10n":"Finale di gelatina","lv10d":"Finale del primo capitolo. ★ Debutta il mega boss, molto più duro di qualsiasi boss normale. (Uno ancora più spaventoso attende ogni 10 livelli.)",
"genName":"{0} {1}","genBossName":"Boss di {0}: {1}",
"genDescBoss":"★ Finale del capitolo {0}: il mega boss «{1}» tiene la linea, più forte del capitolo precedente sotto ogni aspetto.",
"genDescOpener":"Ingresso in «{0}». La pressione cala dopo il capitolo precedente — preparati a risalire.",
"genDescMid":"«{0}» mantiene la pressione. Vita dei nemici e densità di comparsa continuano a salire.",
"tFrenzy":"FRENESIA! Velocità d'attacco doppia","tMidBoss":"Scrigno dorato di sovraccarico! Un cuore ripristinato",
}
