# -*- coding: utf-8 -*-
DE = {
"play":"SPIEL STARTEN","playLv":"Level {0}","replayLv":"Wiederholen · Level {0}","playLast":"Letztes Level erneut",
"shop":"Bonbonladen","back":"◀ Zurück","cancel":"Abbrechen","max":"MAX",
"resetBtn":"Von Level 1 neu starten","resetQ":"Wirklich von Level 1 neu starten?",
"resetSub":"Dein Fortschritt wird gelöscht. Das lässt sich nicht rückgängig machen.","resetOk":"Ja, neu starten",
"shopTitle":"Bonbonladen","shopCoins":"{0} Bonbonmünzen",
"shopHint":"Dauerhafte Verbesserungen, ab dem Start jedes Laufs aktiv. Kommst du nicht weiter? Sammle Münzen und werde stärker.",
"pauseMsg":"Pausiert","resume":"▶ Weiter","toMenu":"Hauptmenü",
"next":"Nächstes Level ▶","again":"Nochmal spielen","saveShot":"Karte speichern",
"clear":"GESCHAFFT!","gameover":"GAME OVER",
"nmWin":"Geschafft! {0} Gegner besiegt","nmClose":"Du kamst bis {0}% — nur noch {1}s bis zum Sieg!","nmFar":"{0}% erreicht · {1} Gegner",
"coinGain":"+{0} Bonbonmünzen","coinTotal":"({0} gesamt)",
"allClear":"ALLES GESCHAFFT","stageOf":"Level {0} / {1}","congrats":"Alle Level geschafft!",
"allClearDesc":"Du hast alle {0} Level bezwungen. Spiel nochmal und jage eine bessere Zeit.","bossCount":"Boss ×{0}",
"cardTitle":"LV.{0} AUFSTIEG! Wähle eine","evolve":"EVOLUTION","newWeapon":"NEU","lvTag":"Lv.{0}","upgradeTag":"VERSTÄRKT",
"hudLv":"LV.{0}","hudKills":"Besiegt {0}","hudStage":"Level {0} · {1} ({2})",
"hudGoo":"Glibber {0}%  SCH +{1}%","hudSpeed":"Tempo ×{0}","killBoss":"BESIEGE DEN BOSS!",
"bossWarn":"⚠ {0} NÄHERT SICH","superBossTag":"⚠️ MEGABOSS · ",
"hintMove":"Bildschirm berühren und ziehen, um dich zu bewegen","hintDash":"Unten links » = Sprint in Laufrichtung (unverwundbar)",
"hintHearts":"Ohne Herzen ist Schluss — überlebe durch Ausweichen","hintChest":"Folge dem Pfeil — dort ist eine Truhe",
"noTouch":"⚠ Keine Touch-Eingaben erkannt",
"tShield":"Schild hat geblockt!","tShieldGain":"SCHILD","tFreeze":"EINGEFROREN!","tRevive":"🕯️ Wiederbelebt! Noch {0}",
"tAllMaxHeart":"Alles maximiert → Herz aufgefüllt!","tAllMaxGem":"Alles maximiert → Kristallregen!",
"tNuke":"☢️ NUKE! {0} Gegner ausgelöscht","tBossIn":"{0} erscheint!","tSuperBossIn":"⚠️ MEGABOSS: {0}!",
"w_bubble_n":"Blasen-Druckspritze","w_bubble_d":"Schnelle Geradeausschüsse · SCH {0}",
"w_graffiti_n":"Regenbogen-Graffitisprüher","w_graffiti_d":"Streuschuss · {0} Schuss · hinterlässt Glibber",
"w_yoyo_n":"Leuchtendes Bumerang-Jo-Jo","w_yoyo_d":"Kreisender Wurf · durchdringt alles",
"e_bubble_n":"Neon-Glibberregen","e_bubble_d":"Glibberregen über den ganzen Bildschirm, verlangsamt Gegner",
"e_graffiti_n":"Regenbogen-Glibberteppich","e_graffiti_d":"Versprühter Glibber entzündet sich selbst in Ketten",
"e_yoyo_n":"Schwerkraft-Jo-Jo","e_yoyo_d":"Zieht Gegner und Kristalle in die Mitte und zermalmt sie",
"u_sticky_n":"Klebriger Sirup","u_sticky_d":"Getroffene Gegner kleben 2s fest, halbes Tempo",
"u_sticky_d2":"Hält 3,5s und springt auf Gegner in der Nähe über",
"u_chain_n":"Kettendetonation","u_chain_d":"30% Chance, den Glibber unter besiegten Gegnern zu zünden",
"u_chain_d2":"Chance auf 60%, größerer Explosionsradius",
"u_mine_n":"Ätzender Glibber","u_mine_d":"Gegner im Glibber erleiden Schaden über Zeit","u_mine_d2":"Doppelter Schaden, Glibber hält länger",
"u_freeze_n":"Eisbonbon-Rolle","u_freeze_d":"Am Ende eines Sprints Gegner in der Nähe 1,6s einfrieren",
"u_shield_n":"Donut-Schild","u_shield_d":"Alle 18s ein Schild, blockt einen Treffer",
"u_shield_d2":"Stattdessen alle 10s, bis zu 2 stapelbar",
"u_frenzy_n":"Raserei-Lolli","u_frenzy_d":"Alle 25 Kills 4s doppeltes Angriffstempo","u_frenzy_d2":"Stattdessen alle 15 Kills, 5s lang",
"u_split_n":"Teilungsgummi","u_split_d":"25% Chance, dass ein Kill 3 Splitter verschießt","u_split_d2":"Chance auf 50%, 5 Splitter",
"u_rage_n":"Volle-Herzen-Wut","u_rage_d":"+45% Schaden bei vollen Herzen (verfällt bei Treffer)",
"u_panic_n":"Erste-Hilfe-Lutscher","u_panic_d":"Nach einem Treffer 3s +75% Tempo und längere Unverwundbarkeit",
"u_greed_n":"Gier-Karneval","u_greed_d":"Jeder Kristall gibt 1 EP extra","u_greed_d2":"Nochmal 1 EP mehr, Kristalle leuchten größer",
"u_cd_n":"Geschmeidige Rolle","u_cd_d":"Sprint-Abklingzeit -0,8s","u_cd_d2":"Weitere -0,6s und längere Sprintdistanz",
"u_regen_n":"Gummi-Regeneration","u_regen_d":"Alle 40s ein Herz zurück","u_regen_d2":"Stattdessen alle 25s",
"u_rangeUp_n":"Bonbon-Fernrohr","u_rangeUp_d":"Zielerfassung eine Stufe weiter — sieh sie, bevor du schießt",
"u_rangeUp_d2":"Noch eine Stufe, nahe am Limit der Waffe",
"m_hearts_n":"Bonbonherz-Schutz","m_hearts_d":"Start-Herzen +{0} ({1} gesamt)",
"m_dmg_n":"Zuckerguss-Klinge","m_dmg_d":"Startschaden +{0}%",
"m_aspd_n":"Schnellrührer","m_aspd_d":"Start-Angriffstempo +{0}%",
"m_wep_n":"Lieblingswaffe","m_wep_d":"Start-Waffenstufe +{0}",
"m_range_n":"Weitsicht-Linse","m_range_d":"Start-Angriffsreichweite +{0}",
"m_xp_n":"Kristall-Affinität","m_xp_d":"EP-Gewinn +{0}%",
"m_pickup_n":"Magnet-Anhänger","m_pickup_d":"Kristall-Aufsammelradius +{0}",
"m_dash_n":"Rollmeister","m_dash_d":"Sprint-Abklingzeit -{0}s",
"m_revive_n":"Wiedergeburtskerze","m_revive_d":"{0}× an Ort und Stelle wiederbeleben (pro Level)",
"m_coin_n":"Münzenjäger","m_coin_d":"Verdiente Bonbonmünzen +{0}%",
"b1":"Überstunden-Akte","b2":"Ungelesene Nachrichten","b3":"Seelenraub-Wecker",
"sb0":"Der KPI-Koloss","sb1":"Montags-Meeting-Dämon","sb2":"Endlos-Überstunden-Geist",
"sb3":"Ignorierte-Nachricht-Unhold","sb4":"Jahresgespräch-Asura","sb5":"Postfach-Überlauf-Fürst",
"sb6":"Schwarzes-Loch-Pensum","sb7":"Übergabe-Wiedergänger","sb8":"Der stille Richter","sb9":"Letztes KPI-Urteil",
"c_heart_n":"Herzbonbon","c_heart_go":"Ein Herz wiederhergestellt!","c_heart_full":"Herzen voll → Kristallregen!",
"c_nuke_n":"Bonbonregen","c_nuke_go":"{0} Geschosse gelöscht!",
"c_speed_n":"Blitzbonbon","c_speed_go":"9s doppeltes Angriffstempo!",
"c_rain_n":"Regenbogenbonbon","c_rain_go":"7s unverwundbar!",
"c_gold_n":"Münzbonbon","c_gold_go":"Kristallregen!",
"c_ice_n":"Eisbonbon","c_ice_go":"{0} Gegner eingefroren!",
"c_fire_n":"Feuerbonbon","c_fire_go":"Glibber entzündet!",
"c_power_n":"Kraftbonbon","c_power_go":"10s +40% Schaden!",
"tier0":"Neuling","tier1":"Eingewöhnt","tier2":"Geübt","tier3":"Herausforderung","tier4":"Inferno",
"tier5":"Abgrund","tier6":"Albtraum","tier7":"Fegefeuer","tier8":"Leere","tier9":"Asura",
"tier10":"Unterwelt","tier11":"Apokalypse","tier12":"Göttlich","tier13":"Endzeit",
"lv1n":"Wackelpudding-Kita","lv1d":"Lerne das Ziehen zur Bewegung. Langsame Gegner, wenig Leben, kein Gegenangriff.",
"lv2n":"Gummibärchen-Wiese","lv2d":"Dieselben Gegner, nur mehr davon. Übe, mit dem Sprint aus der Umzingelung zu kommen.",
"lv3n":"Neon-Spielplatz","lv3d":"★ Hasen kommen: doppelt so schnell wie Schleim. Weniger Gegner, damit du dich einstellen kannst.",
"lv4n":"Knallbrause-Stadt","lv4d":"Mehr Hasen. Jetzt musst du dich wirklich bewegen.",
"lv5n":"Klebrige Marmeladenfabrik","lv5d":"★ Drohnen kommen: sie schießen aus der Distanz. Nutze die Sprint-Unverwundbarkeit, um durch Geschosse zu gehen.",
"lv6n":"Kugelhagel-Bonbonhaus","lv6d":"Dichtere Geschosse, längeres Level. Ab hier musst du deine Herzen ernsthaft verwalten.",
"lv7n":"Explosive Gummimine","lv7d":"★ Bomber kommen: sie explodieren aus der Nähe, entzünden aber auch Glibber. Drei Bosse.",
"lv8n":"Außer-Rand-Bonbonstadt","lv8d":"Alle vier Gegnertypen. Nichts Neues — reines Können.",
"lv9n":"Karamell-Inferno","lv9d":"Leben, Tempo und Geschossgeschwindigkeit allesamt erhöht.",
"lv10n":"Wackelpudding-Finale","lv10d":"Finale des ersten Kapitels. ★ Der Megaboss debütiert, weit zäher als jeder normale Boss. (Alle 10 Level wartet ein noch schlimmerer.)",
"genName":"{0} {1}","genBossName":"{0}-Boss: {1}",
"genDescBoss":"★ Finale von Kapitel {0}: Megaboss \"{1}\" hält die Stellung, in jeder Hinsicht stärker als das letzte Kapitel.",
"genDescOpener":"Eintritt in \"{0}\". Der Druck lässt nach dem letzten Kapitel kurz nach — bereite dich auf den nächsten Anstieg vor.",
"genDescMid":"\"{0}\" hält den Druck aufrecht. Gegnerleben und Spawndichte steigen weiter.",
"tFrenzy":"RASEREI! Doppeltes Angriffstempo","tMidBoss":"Goldene Überladungstruhe! Ein Herz zurück",
}
FR = {
"play":"COMMENCER","playLv":"Niveau {0}","replayLv":"Rejouer · Niveau {0}","playLast":"Rejouer le dernier niveau",
"shop":"Confiserie","back":"◀ Retour","cancel":"Annuler","max":"MAX",
"resetBtn":"Recommencer au niveau 1","resetQ":"Recommencer au niveau 1 ?",
"resetSub":"Ta progression sera effacée. Cette action est irréversible.","resetOk":"Oui, recommencer",
"shopTitle":"Confiserie","shopCoins":"{0} pièces bonbon",
"shopHint":"Améliorations permanentes, actives dès le début de chaque partie. Bloqué sur un niveau ? Reviens gagner des pièces et deviens plus fort.",
"pauseMsg":"En pause","resume":"▶ Reprendre","toMenu":"Menu principal",
"next":"Niveau suivant ▶","again":"Rejouer","saveShot":"Enregistrer la carte",
"clear":"RÉUSSI !","gameover":"GAME OVER",
"nmWin":"Réussi ! {0} ennemis éliminés","nmClose":"Tu as atteint {0}% — encore {1}s et c'était gagné !","nmFar":"{0}% atteint · {1} éliminés",
"coinGain":"+{0} pièces bonbon","coinTotal":"({0} au total)",
"allClear":"TOUT TERMINÉ","stageOf":"Niveau {0} / {1}","congrats":"Tous les niveaux terminés !",
"allClearDesc":"Tu as battu les {0} niveaux. Rejoue et vise un meilleur temps.","bossCount":"Boss ×{0}",
"cardTitle":"NIV.{0} ! Choisis une carte","evolve":"ÉVOLUTION","newWeapon":"NOUVEAU","lvTag":"Niv.{0}","upgradeTag":"AMÉLIORÉ",
"hudLv":"NIV.{0}","hudKills":"Éliminés {0}","hudStage":"Niveau {0} · {1} ({2})",
"hudGoo":"Gelée {0}%  DÉG +{1}%","hudSpeed":"Vitesse ×{0}","killBoss":"ÉLIMINE LE BOSS !",
"bossWarn":"⚠ {0} ARRIVE","superBossTag":"⚠️ MÉGA-BOSS · ",
"hintMove":"Touche l'écran n'importe où et glisse pour te déplacer","hintDash":"» en bas à gauche = dash dans ta direction (invincibilité)",
"hintHearts":"Plus de cœurs, c'est fini — survis en esquivant","hintChest":"Suis la flèche — il y a un coffre",
"noTouch":"⚠ Aucun événement tactile détecté",
"tShield":"Le bouclier a bloqué !","tShieldGain":"BOUCLIER","tFreeze":"GELÉ !","tRevive":"🕯️ Réanimé ! {0} restante(s)",
"tAllMaxHeart":"Tout au max → cœur restauré !","tAllMaxGem":"Tout au max → pluie de gemmes !",
"tNuke":"☢️ NUKE ! {0} ennemis balayés","tBossIn":"{0} apparaît !","tSuperBossIn":"⚠️ MÉGA-BOSS : {0} !",
"w_bubble_n":"Pistolet à bulles sous pression","w_bubble_d":"Tirs rapides en ligne · DÉG {0}",
"w_graffiti_n":"Bombe à graffiti arc-en-ciel","w_graffiti_d":"Tir en cône · {0} projectiles · laisse de la gelée",
"w_yoyo_n":"Yo-yo boomerang lumineux","w_yoyo_d":"Lancer orbital · transperce tout",
"e_bubble_n":"Déluge de gelée néon","e_bubble_d":"Pluie de gelée sur tout l'écran, ralentit les ennemis",
"e_graffiti_n":"Tapis de gelée arc-en-ciel","e_graffiti_d":"La gelée projetée s'embrase en chaîne toute seule",
"e_yoyo_n":"Yo-yo trou noir","e_yoyo_d":"Aspire ennemis et gemmes vers le centre et les broie",
"u_sticky_n":"Sirop collant","u_sticky_d":"Les ennemis touchés sont collés 2s, vitesse divisée par deux",
"u_sticky_d2":"Dure 3,5s et se propage aux ennemis proches",
"u_chain_n":"Détonation en chaîne","u_chain_d":"30% de chances d'enflammer la gelée sous un ennemi tué",
"u_chain_d2":"Chances portées à 60%, rayon d'explosion accru",
"u_mine_n":"Gelée corrosive","u_mine_d":"Les ennemis dans la gelée subissent des dégâts continus","u_mine_d2":"Dégâts doublés, la gelée dure plus longtemps",
"u_freeze_n":"Roulade glacée","u_freeze_d":"À la fin d'un dash, gèle les ennemis proches 1,6s",
"u_shield_n":"Bouclier donut","u_shield_d":"Toutes les 18s, un bouclier bloque un coup",
"u_shield_d2":"Toutes les 10s à la place, cumulable 2 fois",
"u_frenzy_n":"Sucette frénésie","u_frenzy_d":"Tous les 25 kills, vitesse d'attaque doublée 4s","u_frenzy_d2":"Tous les 15 kills, pendant 5s",
"u_split_n":"Bonbon fissile","u_split_d":"25% de chances qu'un kill projette 3 éclats","u_split_d2":"50% de chances, 5 éclats",
"u_rage_n":"Rage à cœur plein","u_rage_d":"+45% de dégâts si les cœurs sont pleins (perdu au moindre coup)",
"u_panic_n":"Sucette premiers secours","u_panic_d":"+75% de vitesse pendant 3s après un coup, invincibilité prolongée",
"u_greed_n":"Carnaval de l'avidité","u_greed_d":"Chaque gemme donne 1 XP de plus","u_greed_d2":"Encore 1 XP, et les gemmes brillent plus gros",
"u_cd_n":"Roulade fluide","u_cd_d":"Recharge du dash -0,8s","u_cd_d2":"-0,6s de plus, et dash plus long",
"u_regen_n":"Régénération gélifiée","u_regen_d":"Un cœur récupéré toutes les 40s","u_regen_d2":"Toutes les 25s à la place",
"u_rangeUp_n":"Longue-vue en sucre","u_rangeUp_d":"Portée de visée automatique élargie d'un cran — vois-les avant de tirer",
"u_rangeUp_d2":"Un cran de plus, proche de la limite de l'arme",
"m_hearts_n":"Garde cœur-bonbon","m_hearts_d":"Cœurs de départ +{0} ({1} au total)",
"m_dmg_n":"Lame de glaçage","m_dmg_d":"Dégâts de départ +{0}%",
"m_aspd_n":"Fouet rapide","m_aspd_d":"Vitesse d'attaque de départ +{0}%",
"m_wep_n":"Arme favorite","m_wep_d":"Niveau de l'arme principale +{0}",
"m_range_n":"Lentille longue portée","m_range_d":"Portée d'attaque de départ +{0}",
"m_xp_n":"Affinité aux gemmes","m_xp_d":"Gain d'XP +{0}%",
"m_pickup_n":"Aimant à gemmes","m_pickup_d":"Rayon de ramassage +{0}",
"m_dash_n":"Maître de la roulade","m_dash_d":"Recharge du dash -{0}s",
"m_revive_n":"Bougie de renaissance","m_revive_d":"Réanimation sur place {0} fois (par niveau)",
"m_coin_n":"Chasseur de pièces","m_coin_d":"Pièces bonbon gagnées +{0}%",
"b1":"Paperasse d'heures sup","b2":"Messages non lus","b3":"Réveil voleur d'âmes",
"sb0":"Le Colosse KPI","sb1":"Démon de la réunion du lundi","sb2":"Spectre des heures sup infinies",
"sb3":"Fléau du message ignoré","sb4":"Asura de l'entretien annuel","sb5":"Seigneur de la boîte pleine",
"sb6":"Trou noir de la charge","sb7":"Revenant de la passation","sb8":"Le Juge silencieux","sb9":"Jugement KPI final",
"c_heart_n":"Bonbon cœur","c_heart_go":"Un cœur restauré !","c_heart_full":"Cœurs pleins → pluie de gemmes !",
"c_nuke_n":"Pluie de bonbons","c_nuke_go":"{0} projectiles effacés !",
"c_speed_n":"Bonbon éclair","c_speed_go":"Vitesse d'attaque doublée 9s !",
"c_rain_n":"Bonbon arc-en-ciel","c_rain_go":"Invincible 7s !",
"c_gold_n":"Bonbon doré","c_gold_go":"Pluie de gemmes !",
"c_ice_n":"Bonbon glacé","c_ice_go":"{0} ennemis gelés !",
"c_fire_n":"Bonbon de feu","c_fire_go":"Gelée enflammée !",
"c_power_n":"Bonbon puissance","c_power_go":"+40% de dégâts pendant 10s !",
"tier0":"Débutant","tier1":"En main","tier2":"Aguerri","tier3":"Défi","tier4":"Enfer",
"tier5":"Abysse","tier6":"Cauchemar","tier7":"Purgatoire","tier8":"Néant","tier9":"Asura",
"tier10":"Outre-monde","tier11":"Apocalypse","tier12":"Divin","tier13":"Finalité",
"lv1n":"Maternelle de gelée","lv1d":"Apprends à glisser pour te déplacer. Ennemis lents, peu de vie, aucune riposte.",
"lv2n":"Prairie de bonbons","lv2d":"Les mêmes ennemis, mais plus nombreux. Entraîne-toi à sortir des mêlées avec le dash.",
"lv3n":"Terrain de jeu néon","lv3d":"★ Les lapins arrivent : deux fois plus rapides que les slimes. Moins d'ennemis pour t'adapter.",
"lv4n":"Ville pétillante","lv4d":"Plus de lapins. Il faut vraiment bouger maintenant.",
"lv5n":"Usine de confiture collante","lv5d":"★ Les drones arrivent : ils tirent à distance. Traverse les tirs grâce à l'invincibilité du dash.",
"lv6n":"Maison de bonbons mitraillée","lv6d":"Tirs plus denses, niveau plus long. À partir d'ici, gère sérieusement tes cœurs.",
"lv7n":"Mine de bonbons explosifs","lv7d":"★ Les kamikazes arrivent : ils explosent de près, mais enflamment aussi la gelée. Trois boss.",
"lv8n":"Cité bonbon déchaînée","lv8d":"Les quatre types d'ennemis. Rien de nouveau — pure exécution.",
"lv9n":"Enfer de caramel","lv9d":"Vie, vitesse et vitesse des projectiles toutes augmentées.",
"lv10n":"Finale de gelée","lv10d":"Final du premier chapitre. ★ Le méga-boss fait ses débuts, bien plus coriace qu'un boss normal. (Un autre, plus terrifiant, attend tous les 10 niveaux.)",
"genName":"{0} {1}","genBossName":"Boss de {0} : {1}",
"genDescBoss":"★ Final du chapitre {0} : le méga-boss « {1} » tient la ligne, plus fort que le chapitre précédent à tous les niveaux.",
"genDescOpener":"Entrée dans « {0} ». La pression retombe après le chapitre précédent — prépare-toi à remonter.",
"genDescMid":"« {0} » maintient la pression. La vie des ennemis et la densité d'apparition continuent d'augmenter.",
"tFrenzy":"FRÉNÉSIE ! Vitesse d'attaque doublée","tMidBoss":"Coffre de surcharge doré ! Un cœur restauré",
}
