# -*- coding: utf-8 -*-
# 英文（預設語言）＝所有 key 的權威來源。其他語言缺 key 時會自動回退到英文。
EN = {
# ── 主選單 / 通用 ──
"play":"START GAME","playLv":"Stage {0}","replayLv":"Replay · Stage {0}","playLast":"Replay Final Stage",
"shop":"Candy Shop","back":"◀ Back","cancel":"Cancel","max":"MAX",
"resetBtn":"Restart from Stage 1","resetQ":"Restart from Stage 1?",
"resetSub":"Your stage progress will be erased. This cannot be undone.","resetOk":"Yes, restart",
# ── 糖果屋 ──
"shopTitle":"Candy Shop","shopCoins":"{0} Candy Coins",
"shopHint":"Permanent upgrades, active from the start of every run. Stuck on a stage? Come back, earn coins and get stronger.",
# ── 暫停 / 結算 ──
"pauseMsg":"Paused","resume":"▶ Resume","toMenu":"Main Menu",
"next":"Next Stage ▶","again":"Play Again","saveShot":"Save Card",
"clear":"CLEAR!","gameover":"GAME OVER",
"nmWin":"Cleared! {0} kills","nmClose":"You reached {0}% — just {1}s more to clear it!","nmFar":"Reached {0}% · {1} kills",
"coinGain":"+{0} Candy Coins","coinTotal":"({0} total)",
# ── 關卡資訊 ──
"allClear":"ALL CLEAR","stageOf":"Stage {0} / {1}","congrats":"All stages cleared!",
"allClearDesc":"You beat all {0} stages. Play again and chase a faster time.","bossCount":"Boss ×{0}",
# ── 升級卡 ──
"cardTitle":"LV.{0} UP! Pick one","evolve":"EVOLVE","newWeapon":"NEW","lvTag":"Lv.{0}","upgradeTag":"UPGRADE",
# ── HUD ──
"hudLv":"LV.{0}","hudKills":"Kills {0}","hudStage":"Stage {0} · {1} ({2})",
"hudGoo":"Goo {0}%  DMG +{1}%","hudSpeed":"Speed ×{0}","killBoss":"KILL THE BOSS!",
"bossWarn":"⚠ {0} INCOMING","superBossTag":"⚠️ MEGA BOSS · ",
"hintMove":"Touch anywhere and drag to move","hintDash":"Bottom-left » = dash in your move direction (i-frames)",
"hintHearts":"Lose all hearts and it's over — survive by dodging","hintChest":"Follow the arrow — there's a chest there",
"noTouch":"⚠ No touch events detected",
# ── 提示訊息 ──
"tShield":"Shield blocked it!","tShieldGain":"SHIELD","tFreeze":"FROZEN!","tRevive":"🕯️ Revived! {0} left",
"tAllMaxHeart":"All maxed → heart restored!","tAllMaxGem":"All maxed → gem shower!",
"tNuke":"☢️ NUKE! {0} minions wiped","tBossIn":"{0} appears!","tSuperBossIn":"⚠️ MEGA BOSS: {0}!",
# ── 武器 ──
"w_bubble_n":"Bubble Pressure Blaster","w_bubble_d":"Fast straight shots · DMG {0}",
"w_graffiti_n":"Rainbow Graffiti Sprayer","w_graffiti_d":"Cone spread · {0} shots · leaves goo",
"w_yoyo_n":"Glowing Boomerang Yo-yo","w_yoyo_d":"Orbiting throw · pierces everything",
"e_bubble_n":"Neon Goo Downpour","e_bubble_d":"Goo rain across the screen, slows enemies",
"e_graffiti_n":"Rainbow Goo Carpet","e_graffiti_d":"Sprayed goo chain-ignites on its own",
"e_yoyo_n":"Gravity Void Yo-yo","e_yoyo_d":"Pulls minions and gems into the centre and grinds them",
# ── 升級卡（16 張）──
"u_sticky_n":"Sticky Syrup","u_sticky_d":"Enemies you hit are stuck for 2s, half speed",
"u_sticky_d2":"Stick lasts 3.5s and spreads to nearby enemies",
"u_chain_n":"Chain Detonation","u_chain_d":"30% chance to ignite the goo under a killed enemy",
"u_chain_d2":"Chance up to 60%, bigger blast radius",
"u_mine_n":"Corrosive Goo","u_mine_d":"Enemies standing in goo take damage over time",
"u_mine_d2":"Double damage, and goo lasts longer",
"u_freeze_n":"Ice Candy Roll","u_freeze_d":"When a dash ends, freeze nearby enemies for 1.6s",
"u_shield_n":"Donut Shield","u_shield_d":"Every 18s gain a shield that blocks one hit",
"u_shield_d2":"Every 10s instead, stacks up to 2",
"u_frenzy_n":"Frenzy Lollipop","u_frenzy_d":"Every 25 kills, double attack speed for 4s",
"u_frenzy_d2":"Every 15 kills instead, lasts 5s",
"u_split_n":"Splitting Gummy","u_split_d":"25% chance a kill sprays 3 shards",
"u_split_d2":"Chance up to 50%, sprays 5 shards",
"u_rage_n":"Full-Heart Rage","u_rage_d":"+45% damage while hearts are full (lost on any hit)",
"u_panic_n":"First-Aid Lolly","u_panic_d":"+75% move speed for 3s after being hit, longer i-frames",
"u_greed_n":"Greed Carnival","u_greed_d":"Every gem gives 1 extra XP",
"u_greed_d2":"1 more XP again, and gems glow bigger",
"u_cd_n":"Smooth Roll","u_cd_d":"Dash cooldown -0.8s","u_cd_d2":"-0.6s more, and longer dash distance",
"u_regen_n":"Gummy Regen","u_regen_d":"Restore one heart every 40s","u_regen_d2":"Every 25s instead",
"u_rangeUp_n":"Candy Spyglass","u_rangeUp_d":"Auto-target range widens one step — see them before you shoot them",
"u_rangeUp_d2":"One more step, close to the weapon's own limit",
# ── 永久強化（10 項）──
"m_hearts_n":"Candy Heart Guard","m_hearts_d":"Starting hearts +{0} ({1} total)",
"m_dmg_n":"Frosting Blade","m_dmg_d":"Starting damage +{0}%",
"m_aspd_n":"Rapid Whisk","m_aspd_d":"Starting attack speed +{0}%",
"m_wep_n":"Favourite Weapon","m_wep_d":"Starting main weapon level +{0}",
"m_range_n":"Long-Sight Lens","m_range_d":"Starting attack range +{0}",
"m_xp_n":"Gem Affinity","m_xp_d":"XP gain +{0}%",
"m_pickup_n":"Magnet Charm","m_pickup_d":"Gem pickup range +{0}",
"m_dash_n":"Roll Master","m_dash_d":"Dash cooldown -{0}s",
"m_revive_n":"Rebirth Candle","m_revive_d":"Revive on the spot {0} time(s) per stage",
"m_coin_n":"Coin Hunter","m_coin_d":"Candy Coins earned +{0}%",
# ── Boss ──
"b1":"Overtime Paperwork","b2":"Unread Messages","b3":"Soul-Stealing Alarm",
"sb0":"The KPI Colossus","sb1":"Monday Standup Demon","sb2":"Endless Overtime Wraith",
"sb3":"Left-on-Read Fiend","sb4":"Annual Review Asura","sb5":"Inbox Overflow Overlord",
"sb6":"Black-Hole Workload","sb7":"Handover Revenant","sb8":"The Silent Judge","sb9":"Final KPI Judgment",
# ── 寶箱 ──
"c_heart_n":"Heart Candy","c_heart_go":"One heart restored!","c_heart_full":"Hearts full → gem shower!",
"c_nuke_n":"Candy Rain","c_nuke_go":"Cleared {0} bullets!",
"c_speed_n":"Lightning Candy","c_speed_go":"Double attack speed for 9s!",
"c_rain_n":"Rainbow Candy","c_rain_go":"Invincible for 7s!",
"c_gold_n":"Coin Candy","c_gold_go":"Gem shower!",
"c_ice_n":"Ice Candy","c_ice_go":"Froze {0} enemies!",
"c_fire_n":"Fire Candy","c_fire_go":"Goo ignited!",
"c_power_n":"Power Candy","c_power_go":"+40% damage for 10s!",
# ── 難度層級（14 個）──
"tier0":"Rookie","tier1":"Getting It","tier2":"Skilled","tier3":"Challenge","tier4":"Inferno",
"tier5":"Abyss","tier6":"Nightmare","tier7":"Purgatory","tier8":"Void","tier9":"Asura",
"tier10":"Netherworld","tier11":"Apocalypse","tier12":"Divine","tier13":"Finality",
# ── 前 10 關（手寫）──
"lv1n":"Jelly Kindergarten","lv1d":"Learn to drag to move. Slow enemies, low HP, no counterattack.",
"lv2n":"Gummy Meadow","lv2d":"Same enemies, just more of them. Practise dashing out of a swarm.",
"lv3n":"Neon Playground","lv3d":"★ Bunnies arrive: twice the speed of slimes. Enemy count drops so you can adjust.",
"lv4n":"Poprock Town","lv4d":"More bunnies. Now you really have to move.",
"lv5n":"Sticky Jam Factory","lv5d":"★ Drones arrive: they shoot from range. Use the dash i-frames to pass through bullets.",
"lv6n":"Bullet Candy House","lv6d":"Denser bullets, longer stage. Start managing your hearts seriously.",
"lv7n":"Exploding Gummy Mine","lv7d":"★ Bombers arrive: they explode up close, but also ignite goo. Three bosses.",
"lv8n":"Runaway Candy City","lv8d":"All four enemy types. Nothing new — pure execution.",
"lv9n":"Caramel Inferno","lv9d":"HP, speed and bullet speed all raised.",
"lv10n":"Jelly Finale","lv10d":"Finale of the first chapter. ★ The Mega Boss debuts, far tougher than any normal boss. (Another, scarier one waits every 10 stages.)",
# ── 第 11~100 關（樣板）──
"genName":"{0} {1}","genBossName":"{0} Boss: {1}",
"genDescBoss":"★ Chapter {0} finale: Mega Boss \"{1}\" holds the line, stronger than the last chapter in every way.",
"genDescOpener":"Entering \"{0}\". Pressure eases off after the last chapter — get ready to climb again.",
"genDescMid":"\"{0}\" keeps the pressure on. Enemy HP and spawn density keep rising.",
"tFrenzy":"FRENZY! Double attack speed","tMidBoss":"Golden overload chest! One heart restored",
}
