"""v70 garden themes and free replayable puzzles, all eleven locales."""
import json
from pathlib import Path
KEYS='gardenPlay festivalTheme0 festivalTheme1 festivalTheme2 festivalHelp festivalRule0 festivalRule1 festivalRule2 festivalBest festivalLevel festivalStart festivalStyle festivalUnlock festivalWin festivalRetryInfo festivalStudy festivalProgress festivalMoves festivalRetry festivalNext festivalReady festivalCell festivalBudget festivalChoose festivalDefault festivalFish festivalRock festivalPearl festivalGoal'.split()
DATA={
'en':'''Village adventures|Picnic parade|Ripple pond|Starlight grove|Three different games, three difficulty levels each. Play freely without spending supplies. Earn medals to decorate your village. No daily limits.|Remember the dishes from left to right. When ready, hide the order and serve the same sequence. A mistake lets you try again.|Tap a neighbouring water tile to guide the fish. Collect all three pearls, then reach the flag within the move budget. Rocks block the way.|Tap a star to switch it and its neighbours above, below, left and right. Light all nine stars. Take as many moves as you need.|Medals {0}/3|Level {0}|Start challenge|Use this village theme|Complete level 1 to unlock this scene. Higher medals add more decorations.|Challenge complete! Medal saved and village theme applied.|Almost! Try again without losing anything.|Study the order. Press Ready when you have memorised it.|Collected {0}/{1}|Moves: {0}|Try again|Next level|Ready — hide the order|Row {0}, column {1}|Moves left: {0}|Choose a challenge|Restore the garden theme|Fish|Rock|Pearl|Finish flag'''.split('|'),
'zh-Hant':'''村莊小冒險|野餐遊行|漣漪池塘|星光樹林|三種不同玩法，各有三階難度。免費挑戰、不扣材料，收集徽章布置村莊，沒有每日次數限制。|記住由左到右的料理順序。準備好後藏起訂單，依序送出相同料理。答錯可重新挑戰。|點相鄰水格帶小魚前進，收齊三顆珍珠，再於步數內抵達旗幟。石頭不能通過。|點一顆星會切換它與上下左右的星光。讓九顆星全部亮起，步數不限。|徽章 {0}/3|難度 {0}|開始挑戰|套用這個村莊主題|完成第一階解鎖場景，更多徽章會增加裝飾。|挑戰成功！徽章已保存，村莊已換上對應主題。|差一點！可以再試，不會扣除資源。|先記住順序，準備好再按開始配餐。|已收集 {0}/{1}|已走 {0} 步|重新挑戰|挑戰下一階|開始配餐・藏起訂單|第 {0} 列、第 {1} 欄|剩餘 {0} 步|選擇挑戰|還原庭院主題|小魚|石頭|珍珠|終點旗幟'''.split('|'),
'zh-Hans':'''村庄小冒险|野餐游行|涟漪池塘|星光树林|三种不同玩法，各有三阶难度。免费挑战、不扣材料，收集徽章装扮村庄，没有每日次数限制。|记住从左到右的料理顺序。准备好后藏起订单，依次送出相同料理。答错可重新挑战。|点相邻水格带小鱼前进，收齐三颗珍珠，再于步数内抵达旗帜。石头不能通过。|点一颗星会切换它与上下左右的星光。让九颗星全部亮起，步数不限。|徽章 {0}/3|难度 {0}|开始挑战|应用这个村庄主题|完成第一阶解锁场景，更多徽章会增加装饰。|挑战成功！徽章已保存，村庄已换上对应主题。|差一点！可以再试，不会扣除资源。|先记住顺序，准备好再按开始配餐。|已收集 {0}/{1}|已走 {0} 步|重新挑战|挑战下一阶|开始配餐・藏起订单|第 {0} 行、第 {1} 列|剩余 {0} 步|选择挑战|还原庭院主题|小鱼|石头|珍珠|终点旗帜'''.split('|'),
'ja':'''村のミニ冒険|ピクニック行進|さざ波の池|星明かりの森|3種類の遊びに各3段階の難度。材料を使わず何度でも挑戦できます。メダルで村を飾りましょう。1日の回数制限はありません。|料理を左から順に覚えましょう。準備ができたら注文を隠し、同じ順で出します。間違えても再挑戦できます。|隣の水マスを押して魚を進めます。真珠3個を集め、残り手数以内に旗へ。岩は通れません。|星を押すと、その星と上下左右の星が切り替わります。9個すべてを灯しましょう。手数制限はありません。|メダル {0}/3|難度 {0}|挑戦する|この村テーマにする|難度1をクリアすると景色が解放。メダルが増えると飾りも増えます。|成功！メダルを保存し、村のテーマを変えました。|惜しい！何も失わずに再挑戦できます。|順番を覚えたら配膳を始めましょう。|獲得 {0}/{1}|手数：{0}|もう一度|次の難度|配膳開始・注文を隠す|{0}行、{1}列|残り{0}手|遊びを選ぶ|元の庭テーマに戻す|魚|岩|真珠|ゴールの旗'''.split('|'),
'ko':'''마을 작은 모험|소풍 행진|물결 연못|별빛 숲|세 가지 놀이에 각각 세 난이도. 재료 소모 없이 자유롭게 도전하고 메달로 마을을 꾸며요. 하루 횟수 제한은 없어요.|왼쪽부터 요리 순서를 외우세요. 준비되면 주문을 숨기고 같은 순서로 내세요. 틀려도 다시 할 수 있어요.|인접한 물칸을 눌러 물고기를 이동해요. 진주 세 개를 모으고 남은 이동 횟수 안에 깃발에 도착하세요. 바위는 통과할 수 없어요.|별을 누르면 그 별과 상하좌우 별이 바뀌어요. 아홉 별을 모두 밝히세요. 이동 횟수 제한은 없어요.|메달 {0}/3|난이도 {0}|도전 시작|이 마을 테마 적용|난이도 1을 깨면 풍경이 열려요. 메달이 늘면 장식도 늘어요.|성공! 메달을 저장하고 마을 테마를 적용했어요.|아까워요! 자원 손실 없이 다시 도전하세요.|순서를 외운 뒤 준비 버튼을 누르세요.|수집 {0}/{1}|이동 {0}회|다시 도전|다음 난이도|준비 완료·주문 숨기기|{0}행 {1}열|남은 이동 {0}회|도전 선택|원래 정원 테마|물고기|바위|진주|도착 깃발'''.split('|'),
'de':'''Dorfabenteuer|Picknickparade|Wellenweiher|Sternenhain|Drei Spiele mit je drei Stufen. Spiele kostenlos ohne Materialverbrauch. Medaillen schmücken dein Dorf. Keine Tageslimits.|Merke dir die Gerichte von links nach rechts. Verbirg die Bestellung, wenn du bereit bist, und serviere dieselbe Folge. Fehler erlauben einen neuen Versuch.|Tippe auf ein benachbartes Wasserfeld. Sammle mit dem Fisch drei Perlen und erreiche die Flagge innerhalb des Zuglimits. Felsen sind gesperrt.|Tippe einen Stern an, um ihn und seine Nachbarn oben, unten, links und rechts umzuschalten. Alle neun sollen leuchten. Ohne Zuglimit.|Medaillen {0}/3|Stufe {0}|Herausforderung starten|Dieses Dorfthema nutzen|Schaffe Stufe 1 für die neue Szene. Weitere Medaillen bringen mehr Dekorationen.|Geschafft! Medaille gespeichert und Dorfthema aktiviert.|Fast! Versuche es erneut, ohne etwas zu verlieren.|Merke dir die Folge. Starte das Servieren, sobald du bereit bist.|Gesammelt {0}/{1}|Züge: {0}|Erneut versuchen|Nächste Stufe|Bereit – Bestellung verbergen|Zeile {0}, Spalte {1}|Züge übrig: {0}|Spiel auswählen|Gartenthema wiederherstellen|Fisch|Fels|Perle|Zielflagge'''.split('|'),
'fr':'''Aventures du village|Parade pique-nique|Étang des rides|Bois étoilé|Trois jeux, chacun avec trois niveaux. Jouez sans dépenser de provisions. Les médailles décorent le village. Aucune limite quotidienne.|Mémorisez les plats de gauche à droite. Cachez la commande quand vous êtes prêt, puis servez dans le même ordre. Une erreur permet de réessayer.|Touchez une case d’eau voisine pour guider le poisson. Ramassez trois perles, puis rejoignez le drapeau avant d’épuiser les déplacements. Les rochers bloquent le passage.|Touchez une étoile pour changer son état et celui de ses voisines du haut, du bas, de gauche et de droite. Allumez les neuf. Déplacements illimités.|Médailles {0}/3|Niveau {0}|Commencer|Appliquer ce thème au village|Terminez le niveau 1 pour ouvrir ce décor. Plus de médailles ajoutent des décorations.|Réussi ! Médaille enregistrée et thème du village appliqué.|Presque ! Réessayez sans rien perdre.|Mémorisez l’ordre, puis commencez le service.|Collecté {0}/{1}|Déplacements : {0}|Réessayer|Niveau suivant|Prêt — cacher la commande|Ligne {0}, colonne {1}|Déplacements restants : {0}|Choisir un jeu|Rétablir le thème du jardin|Poisson|Rocher|Perle|Drapeau d’arrivée'''.split('|'),
'es':'''Aventuras del pueblo|Desfile de pícnic|Estanque de ondas|Arboleda estelar|Tres juegos con tres dificultades cada uno. Juega sin gastar provisiones. Consigue medallas para decorar el pueblo. Sin límite diario.|Recuerda los platos de izquierda a derecha. Cuando estés listo, oculta el pedido y sirve en el mismo orden. Si fallas, puedes repetir.|Toca una casilla de agua vecina para guiar al pez. Reúne tres perlas y llega a la bandera dentro del límite de movimientos. Las rocas bloquean el paso.|Toca una estrella para cambiarla junto con sus vecinas de arriba, abajo, izquierda y derecha. Enciende las nueve. Sin límite de movimientos.|Medallas {0}/3|Dificultad {0}|Empezar desafío|Usar este tema del pueblo|Completa el nivel 1 para abrir este paisaje. Más medallas añaden decoraciones.|¡Logrado! Medalla guardada y tema del pueblo aplicado.|¡Casi! Repite sin perder nada.|Recuerda el orden y empieza a servir cuando estés listo.|Recogido {0}/{1}|Movimientos: {0}|Reintentar|Siguiente nivel|Listo — ocultar pedido|Fila {0}, columna {1}|Movimientos restantes: {0}|Elegir desafío|Restaurar tema del jardín|Pez|Roca|Perla|Bandera de llegada'''.split('|'),
'it':'''Avventure del villaggio|Parata picnic|Stagno increspato|Bosco stellato|Tre giochi con tre difficoltà ciascuno. Gioca senza consumare scorte. Le medaglie decorano il villaggio. Nessun limite giornaliero.|Ricorda i piatti da sinistra a destra. Quando sei pronto, nascondi l’ordine e servi nella stessa sequenza. Se sbagli puoi riprovare.|Tocca una casella d’acqua vicina per guidare il pesce. Raccogli tre perle e raggiungi la bandiera entro il limite di mosse. Le rocce bloccano il passaggio.|Tocca una stella per cambiare il suo stato e quello delle vicine sopra, sotto, a sinistra e a destra. Accendile tutte e nove. Nessun limite di mosse.|Medaglie {0}/3|Difficoltà {0}|Inizia la sfida|Applica questo tema|Supera il livello 1 per sbloccare lo scenario. Altre medaglie aggiungono decorazioni.|Riuscito! Medaglia salvata e tema del villaggio applicato.|Quasi! Riprova senza perdere nulla.|Memorizza l’ordine, poi inizia a servire.|Raccolti {0}/{1}|Mosse: {0}|Riprova|Livello successivo|Pronto — nascondi ordine|Riga {0}, colonna {1}|Mosse rimaste: {0}|Scegli una sfida|Ripristina il tema del giardino|Pesce|Roccia|Perla|Bandiera finale'''.split('|'),
'pt-BR':'''Aventuras da vila|Desfile de piquenique|Lago das ondas|Bosque estrelado|Três jogos com três dificuldades cada. Jogue sem gastar provisões. Ganhe medalhas para decorar a vila. Sem limite diário.|Memorize os pratos da esquerda para a direita. Quando estiver pronto, esconda o pedido e sirva na mesma ordem. Se errar, tente de novo.|Toque numa casa de água vizinha para guiar o peixe. Pegue três pérolas e chegue à bandeira dentro do limite de movimentos. Rochas bloqueiam a passagem.|Toque numa estrela para mudar ela e as vizinhas de cima, baixo, esquerda e direita. Acenda as nove. Sem limite de movimentos.|Medalhas {0}/3|Dificuldade {0}|Começar desafio|Usar este tema na vila|Complete o nível 1 para liberar a paisagem. Mais medalhas adicionam enfeites.|Conseguiu! Medalha salva e tema da vila aplicado.|Quase! Tente de novo sem perder nada.|Memorize a ordem e comece a servir quando estiver pronto.|Coletado {0}/{1}|Movimentos: {0}|Tentar de novo|Próximo nível|Pronto — esconder pedido|Linha {0}, coluna {1}|Movimentos restantes: {0}|Escolher desafio|Restaurar tema do jardim|Peixe|Rocha|Pérola|Bandeira de chegada'''.split('|'),
'ru':'''Приключения деревни|Парад пикников|Пруд с рябью|Звёздная роща|Три игры, по три уровня сложности. Играйте без траты запасов. Медали украшают деревню. Дневных ограничений нет.|Запомните блюда слева направо. Когда будете готовы, скройте заказ и подайте блюда в том же порядке. Ошибка позволяет повторить.|Нажимайте соседнюю водную клетку, чтобы вести рыбку. Соберите три жемчужины и дойдите до флага за отведённые ходы. Камни непроходимы.|Нажмите звезду, чтобы переключить её и соседей сверху, снизу, слева и справа. Зажгите все девять. Число ходов не ограничено.|Медали {0}/3|Сложность {0}|Начать испытание|Применить тему деревни|Пройдите уровень 1, чтобы открыть пейзаж. Новые медали добавляют украшения.|Успех! Медаль сохранена, тема деревни применена.|Почти! Повторите без потери ресурсов.|Запомните порядок и начните подачу, когда будете готовы.|Собрано {0}/{1}|Ходы: {0}|Попробовать снова|Следующий уровень|Готово — скрыть заказ|Ряд {0}, столбец {1}|Осталось ходов: {0}|Выбрать испытание|Вернуть тему сада|Рыбка|Камень|Жемчужина|Финишный флаг'''.split('|')}
if __name__=='__main__':
 p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_text(encoding='utf-8');old=next(x for x in s.splitlines() if x.startswith('const L10N='));d=json.loads(old[11:-1]);assert set(d)==set(DATA)
 for lang,row in DATA.items():
  assert len(row)==len(KEYS),(lang,len(row),len(KEYS));d[lang].update(zip(KEYS,row))
 p.write_text(s.replace(old,'const L10N='+json.dumps(d,ensure_ascii=False)+';'),encoding='utf-8')
