"""Guided restoration loop, all eleven locales; run to update the single-file dictionary."""
import json
from pathlib import Path
KEYS='gardenNextProject gardenProject0 gardenProject1 gardenProject2 gardenUnlock0 gardenUnlock1 gardenUnlock2 gardenFreePlay gardenPetalGoal gardenStepRepair gardenChooseCrop gardenBatchInfo gardenPlantBatch gardenHarvestInfo gardenHarvestBatch gardenRepairInfo gardenGrowInfo gardenGoAdventure gardenSeedInfo gardenCollected gardenRestored'.split()
DATA={
'en':[
'Next restoration','A welcoming cottage','A greener home','Finish your dream cottage','Remove the boards, add flowers and unlock Berry Bloom.','Grow vines around the cottage and unlock Moon Blossom.','Give the cottage its final rose-coloured roof.','Your cottage is complete. Grow flowers or arrange a garden for your visitors.','Petals: {0} / {1}','Restore','Choose a crop','Use {0} seeds. Clear {1} stage(s) to harvest {2} petals.','Plant {0} fields','{0} fields ready: collect {1} petals and get the seeds back.','Harvest {0} fields','Spend {0} petals to restore the cottage. Your new look stays.','Clear {0} more stage(s) for the next harvest. Replaying a cleared stage also counts; waiting does not.','Go to Adventure','No seeds? Clear any stage to earn one, then return to plant.','Harvested: +{0} petals. Seeds returned!','Cottage restored to level {0}!'],
'zh-Hant':[
'下一個修復目標','讓小屋重新溫暖起來','讓綠意爬上小屋','完成夢想小屋','拆掉木板、添上花朵，解鎖莓果花。','讓藤蔓爬上小屋，解鎖月光花。','換上最後的玫瑰色屋頂。','小屋完成了！繼續種花，或布置庭院迎接訪客。','花瓣：{0} / {1}','修復','選擇作物','花費 {0} 顆種子。通關 {1} 次後，可收成 {2} 片花瓣。','播種 {0} 塊田地','{0} 塊田地成熟：可收成 {1} 片花瓣，並拿回種子。','收成 {0} 塊田地','花費 {0} 片花瓣修復小屋，新外觀會永久保留。','再通關 {0} 次就能收成。重玩已過關的關卡也算；放著等待不會成長。','前往冒險','沒有種子？通關任一關可獲得一顆，再回來播種。','收成成功：花瓣 +{0}，種子已歸還！','小屋已修復至第 {0} 級！'],
'zh-Hans':[
'下一个修复目标','让小屋重新温暖起来','让绿意爬上小屋','完成梦想小屋','拆掉木板、添上花朵，解锁莓果花。','让藤蔓爬上小屋，解锁月光花。','换上最后的玫瑰色屋顶。','小屋完成了！继续种花，或布置庭院迎接访客。','花瓣：{0} / {1}','修复','选择作物','花费 {0} 颗种子。通关 {1} 次后，可收获 {2} 片花瓣。','播种 {0} 块田地','{0} 块田地成熟：可收获 {1} 片花瓣，并拿回种子。','收获 {0} 块田地','花费 {0} 片花瓣修复小屋，新外观会永久保留。','再通关 {0} 次就能收获。重玩已通关的关卡也算；等待不会成长。','前往冒险','没有种子？通关任意关卡可获得一颗，再回来播种。','收获成功：花瓣 +{0}，种子已归还！','小屋已修复至第 {0} 级！'],
'ja':[
'次の修復目標','あたたかい家へ','緑に包まれた家へ','夢の家を完成させよう','板を外して花を飾り、ベリーの花を解放。','家にツタを育てて、月光の花を解放。','仕上げにバラ色の屋根にしよう。','家は完成！花を育てたり、庭を飾って訪問者を迎えよう。','花びら：{0} / {1}','修復','作物を選ぶ','種を{0}個使います。{1}回クリアすると花びら{2}枚を収穫。','畑{0}か所に植える','畑{0}か所が収穫可能。花びら{1}枚と種が戻ります。','畑{0}か所を収穫','花びら{0}枚で家を修復。新しい外観は残ります。','あと{0}回クリアすると収穫できます。クリア済みステージでもOK。待つだけでは育ちません。','冒険へ','種がない？どのステージでもクリアすると1個もらえます。戻って植えよう。','収穫：花びら+{0}。種も戻りました！','家をレベル{0}に修復！'],
'ko':[
'다음 복원 목표','따뜻한 집으로','초록빛 집으로','꿈의 집 완성','널빤지를 떼고 꽃을 장식해 베리꽃을 잠금 해제하세요.','집에 덩굴을 키우고 달빛꽃을 잠금 해제하세요.','마지막으로 장밋빛 지붕을 올리세요.','집 완성! 꽃을 기르거나 정원을 꾸며 방문객을 맞이하세요.','꽃잎: {0} / {1}','복원','작물 선택','씨앗 {0}개 사용. 스테이지를 {1}번 클리어하면 꽃잎 {2}개를 수확해요.','밭 {0}곳에 심기','밭 {0}곳 수확 가능: 꽃잎 {1}개를 얻고 씨앗을 돌려받아요.','밭 {0}곳 수확','꽃잎 {0}개로 집을 복원해요. 새 모습은 계속 유지돼요.','{0}번 더 클리어하면 수확해요. 완료한 스테이지를 다시 해도 돼요. 기다리기만 하면 자라지 않아요.','모험으로','씨앗이 없나요? 아무 스테이지나 클리어해 1개를 얻고 돌아와 심으세요.','수확 완료: 꽃잎 +{0}. 씨앗도 돌아왔어요!','집을 {0}레벨로 복원했어요!'],
'de':[
'Nächstes Bauziel','Ein gemütliches Haus','Ein grüneres Zuhause','Vollende dein Traumhaus','Entferne die Bretter, pflanze Blumen und schalte die Beerenblüte frei.','Lass Ranken am Haus wachsen und schalte die Mondblume frei.','Gib dem Haus zum Abschluss ein rosafarbenes Dach.','Dein Haus ist fertig. Züchte Blumen oder gestalte den Garten für Besucher.','Blütenblätter: {0} / {1}','Ausbauen','Pflanze wählen','Kostet {0} Samen. Nach {1} abgeschlossenen Leveln erntest du {2} Blütenblätter.','{0} Felder bepflanzen','{0} Felder reif: {1} Blütenblätter und die Samen zurück.','{0} Felder ernten','Baue das Haus für {0} Blütenblätter aus. Der neue Look bleibt.','Noch {0} Level bis zur Ernte. Bereits geschaffte Level zählen auch; Warten lässt nichts wachsen.','Zum Abenteuer','Keine Samen? Schließe ein beliebiges Level ab, erhalte einen Samen und pflanze ihn ein.','Geerntet: +{0} Blütenblätter. Samen zurückerhalten!','Haus auf Stufe {0} ausgebaut!'],
'fr':[
'Prochaine rénovation','Une maison accueillante','Une maison plus verte','Terminez la maison de vos rêves','Retirez les planches, ajoutez des fleurs et débloquez la fleur de baie.','Faites pousser des lianes et débloquez la fleur de lune.','Terminez la maison avec un toit rose.','La maison est terminée ! Cultivez des fleurs ou aménagez le jardin pour les visiteurs.','Pétales : {0} / {1}','Rénover','Choisir une plante','Coût : {0} graines. Réussissez {1} niveaux pour récolter {2} pétales.','Planter dans {0} champs','{0} champs prêts : récoltez {1} pétales et récupérez les graines.','Récolter {0} champs','Dépensez {0} pétales pour rénover la maison. Son nouvel aspect est permanent.','Encore {0} niveaux à réussir avant la récolte. Rejouer un niveau réussi compte aussi ; attendre ne fait rien pousser.','Partir à l’aventure','Plus de graines ? Réussissez un niveau pour en gagner une, puis revenez planter.','Récolte : +{0} pétales. Graines récupérées !','Maison rénovée au niveau {0} !'],
'es':[
'Próxima restauración','Una casa acogedora','Un hogar más verde','Completa la casa de tus sueños','Retira las tablas, añade flores y desbloquea la flor de baya.','Cultiva enredaderas y desbloquea la flor lunar.','Termina la casa con un tejado rosado.','¡Casa terminada! Cultiva flores o decora el jardín para tus visitantes.','Pétalos: {0} / {1}','Restaurar','Elegir cultivo','Usa {0} semillas. Supera {1} etapas para cosechar {2} pétalos.','Plantar {0} campos','{0} campos listos: recoge {1} pétalos y recupera las semillas.','Cosechar {0} campos','Gasta {0} pétalos para restaurar la casa. Su nuevo aspecto se conserva.','Supera {0} etapas más para cosechar. Repetir etapas superadas también cuenta; esperar no hace crecer las plantas.','Ir a la aventura','¿Sin semillas? Supera cualquier etapa para ganar una y vuelve a plantar.','Cosecha: +{0} pétalos. ¡Semillas recuperadas!','¡Casa restaurada al nivel {0}!'],
'it':[
'Prossimo restauro','Una casa accogliente','Una casa più verde','Completa la casa dei tuoi sogni','Rimuovi le assi, aggiungi fiori e sblocca il fiore di bacca.','Fai crescere i rampicanti e sblocca il fiore lunare.','Completa la casa con un tetto rosa.','Casa completata! Coltiva fiori o decora il giardino per i visitatori.','Petali: {0} / {1}','Restaurare','Scegli una pianta','Usa {0} semi. Supera {1} livelli per raccogliere {2} petali.','Pianta in {0} campi','{0} campi pronti: raccogli {1} petali e recupera i semi.','Raccogli {0} campi','Spendi {0} petali per restaurare la casa. Il nuovo aspetto rimarrà.','Supera altri {0} livelli per raccogliere. Anche ripetere quelli già superati conta; aspettare non fa crescere nulla.','Vai all’avventura','Niente semi? Supera un livello qualsiasi per ottenerne uno e torna a piantare.','Raccolto: +{0} petali. Semi recuperati!','Casa restaurata al livello {0}!'],
'pt-BR':[
'Próxima restauração','Uma casa acolhedora','Um lar mais verde','Complete a casa dos sonhos','Remova as tábuas, acrescente flores e desbloqueie a flor de frutas.','Cultive trepadeiras e desbloqueie a flor da lua.','Finalize a casa com um telhado rosado.','Casa concluída! Cultive flores ou decore o jardim para os visitantes.','Pétalas: {0} / {1}','Restaurar','Escolher planta','Usa {0} sementes. Conclua {1} fases para colher {2} pétalas.','Plantar em {0} campos','{0} campos prontos: colha {1} pétalas e recupere as sementes.','Colher {0} campos','Gaste {0} pétalas para restaurar a casa. O novo visual permanece.','Conclua mais {0} fases para colher. Repetir fases concluídas também conta; esperar não faz as plantas crescerem.','Ir à aventura','Sem sementes? Conclua qualquer fase para ganhar uma e volte a plantar.','Colheita: +{0} pétalas. Sementes devolvidas!','Casa restaurada para o nível {0}!'],
'ru':[
'Следующее улучшение','Уютный домик','Больше зелени','Завершите дом мечты','Уберите доски, добавьте цветы и откройте ягодный цветок.','Вырастите лозы на домике и откройте лунный цветок.','Завершите домик розовой крышей.','Домик готов! Выращивайте цветы или украшайте сад для гостей.','Лепестки: {0} / {1}','Улучшить','Выбрать растение','Нужно семян: {0}. Пройдите этапов: {1}, чтобы собрать лепестки: {2}.','Засеять грядки: {0}','Готово грядок: {0}. Соберите лепестки: {1} и верните семена.','Собрать грядки: {0}','Потратьте лепестки ({0}) на улучшение домика. Новый облик сохранится.','До урожая осталось пройти этапов: {0}. Повторные прохождения тоже считаются; ожидание не даёт роста.','В приключение','Нет семян? Пройдите любой этап, получите одно семя и вернитесь в сад.','Урожай: +{0} лепестков. Семена возвращены!','Домик улучшен до уровня {0}!']
}
if __name__=='__main__':
 p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_text(encoding='utf-8');old=next(x for x in s.splitlines() if x.startswith('const L10N='));d=json.loads(old[11:-1]);assert set(d)==set(DATA)
 for lang,row in DATA.items():
  assert len(row)==len(KEYS),(lang,len(row));d[lang].update(zip(KEYS,row))
 p.write_text(s.replace(old,'const L10N='+json.dumps(d,ensure_ascii=False)+';'),encoding='utf-8')
