"""Garden interface translations; no runtime dependencies."""
import json
from pathlib import Path
KEYS='navGarden gardenTitle gardenHint gardenStock gardenPlot gardenEmpty gardenGrowing gardenReady gardenPlant gardenHarvest gardenHouse gardenUpgrade gardenMax gardenCrop0 gardenCrop1 gardenCrop2 gardenHelp'.split()
ROWS={
'en':['Garden','Candy Garden','Bring seeds home from cleared stages. Grow a garden between adventures.','Seeds: {0} · Petals: {1}','Plot {0}','Ready to plant','Growth: {0}/{1} clears','Ready to harvest','Plant','Harvest','Cottage level {0}/3','Restore · {0} petals','Cottage restored!','Mint Sprout','Berry Bloom','Moon Blossom','One seed per plant. Clear any stage to grow. Harvest returns one seed. Cottage upgrades unlock plants and scenery, not combat power.'],
'zh-Hant':['庭院','糖果庭院','通關帶回種子，在冒險之間種出自己的家園。','種子：{0} · 花瓣：{1}','花圃 {0}','可以種植','成長：通關 {0}/{1} 次','可以收成','種植','收成','小屋等級 {0}/3','修復 · {0} 花瓣','小屋修復完成！','薄荷嫩芽','莓果花','月光花','每次種植消耗一顆種子，通過任意關卡即可成長。收成返還一顆種子。修復小屋解鎖植物與景觀，不增加戰鬥能力。'],
'zh-Hans':['庭院','糖果庭院','通关带回种子，在冒险之间种出自己的家园。','种子：{0} · 花瓣：{1}','花圃 {0}','可以种植','成长：通关 {0}/{1} 次','可以收成','种植','收成','小屋等级 {0}/3','修复 · {0} 花瓣','小屋修复完成！','薄荷嫩芽','莓果花','月光花','每次种植消耗一颗种子，通过任意关卡即可成长。收成返还一颗种子。修复小屋解锁植物与景观，不增加战斗能力。'],
'ja':['庭','お菓子の庭','ステージをクリアして種を持ち帰り、冒険の合間に庭を育てよう。','種：{0} · 花びら：{1}','花壇 {0}','植えられます','成長：クリア {0}/{1} 回','収穫できます','植える','収穫','小屋レベル {0}/3','修復 · 花びら {0}','小屋の修復完了！','ミントの芽','ベリーの花','月光の花','植えるたびに種を1つ消費。どのステージでもクリアすると成長し、収穫で種が1つ戻ります。小屋の修復で植物や景観が増えますが、戦闘能力は変わりません。'],
'ko':['정원','사탕 정원','스테이지를 완료하고 씨앗을 가져와 모험 사이에 정원을 가꾸세요.','씨앗: {0} · 꽃잎: {1}','화단 {0}','심을 수 있어요','성장: {0}/{1}회 완료','수확할 수 있어요','심기','수확','오두막 레벨 {0}/3','복원 · 꽃잎 {0}개','오두막 복원 완료!','민트 새싹','베리꽃','달빛꽃','심을 때 씨앗 1개가 필요합니다. 아무 스테이지나 완료하면 성장하고, 수확하면 씨앗 1개를 돌려받습니다. 오두막을 복원하면 식물과 풍경이 해금되며 전투 능력은 증가하지 않습니다.'],
'de':['Garten','Bonbongarten','Bringe Samen aus geschafften Stufen mit und pflege deinen Garten zwischen Abenteuern.','Samen: {0} · Blütenblätter: {1}','Beet {0}','Bereit zum Pflanzen','Wachstum: {0}/{1} Stufen','Erntebereit','Pflanzen','Ernten','Hütte Stufe {0}/3','Restaurieren · {0} Blütenblätter','Hütte restauriert!','Minzspross','Beerenblüte','Mondblume','Eine Saat pro Pflanze. Jede geschaffte Stufe lässt sie wachsen. Jede Ernte gibt eine Saat zurück. Die Hütte schaltet Pflanzen und Landschaft frei, keine Kampfkraft.'],
'fr':['Jardin','Jardin sucré','Rapportez des graines des niveaux réussis et cultivez votre jardin entre deux aventures.','Graines : {0} · Pétales : {1}','Parcelle {0}','Prête à planter','Croissance : {0}/{1} niveaux','Prête à récolter','Planter','Récolter','Maisonnette niveau {0}/3','Restaurer · {0} pétales','Maisonnette restaurée !','Pousse de menthe','Fleur de baie','Fleur de lune','Une graine par plante. Réussissez un niveau pour la faire pousser. La récolte rend une graine. La maisonnette débloque des plantes et des décors, sans bonus de combat.'],
'es':['Jardín','Jardín de caramelos','Trae semillas de las fases superadas y cultiva tu jardín entre aventuras.','Semillas: {0} · Pétalos: {1}','Parcela {0}','Lista para plantar','Crecimiento: {0}/{1} fases','Lista para cosechar','Plantar','Cosechar','Casita nivel {0}/3','Restaurar · {0} pétalos','¡Casita restaurada!','Brote de menta','Flor de baya','Flor lunar','Una semilla por planta. Supera cualquier fase para que crezca. Cada cosecha devuelve una semilla. La casita desbloquea plantas y paisajes, sin aumentar el poder de combate.'],
'it':['Giardino','Giardino di caramelle','Porta a casa semi dai livelli superati e coltiva il giardino tra le avventure.','Semi: {0} · Petali: {1}','Aiuola {0}','Pronta per la semina','Crescita: {0}/{1} livelli','Pronta per il raccolto','Pianta','Raccogli','Casetta livello {0}/3','Restaura · {0} petali','Casetta restaurata!','Germoglio di menta','Fiore di bacca','Fiore lunare','Un seme per pianta. Supera un livello qualsiasi per farla crescere. Il raccolto restituisce un seme. La casetta sblocca piante e paesaggi, non potenza in combattimento.'],
'pt-BR':['Jardim','Jardim de doces','Traga sementes das fases vencidas e cultive seu jardim entre aventuras.','Sementes: {0} · Pétalas: {1}','Canteiro {0}','Pronto para plantar','Crescimento: {0}/{1} fases','Pronto para colher','Plantar','Colher','Chalé nível {0}/3','Restaurar · {0} pétalas','Chalé restaurado!','Broto de menta','Flor de frutas','Flor da lua','Uma semente por planta. Vença qualquer fase para fazê-la crescer. Cada colheita devolve uma semente. O chalé libera plantas e cenários, sem aumentar o poder de combate.'],
'ru':['Сад','Конфетный сад','Приносите семена с пройденных этапов и растите сад между приключениями.','Семена: {0} · Лепестки: {1}','Грядка {0}','Можно сажать','Рост: {0}/{1} этапов','Можно собирать','Посадить','Собрать','Домик: уровень {0}/3','Починить · {0} лепестков','Домик восстановлен!','Росток мяты','Ягодный цветок','Лунный цветок','Одно семя на растение. Проходите любые этапы для роста. Урожай возвращает одно семя. Домик открывает растения и декорации, не увеличивая боевую мощь.']}
KEYS.append('gardenCropInfo')
for lang,text in dict(zip(ROWS,[
'{0} stage clears → {1} petals','通關 {0} 次 → {1} 花瓣','通关 {0} 次 → {1} 花瓣','{0}回クリア → 花びら{1}枚','{0}회 완료 → 꽃잎 {1}개','{0} Stufen → {1} Blütenblätter','{0} niveaux → {1} pétales','{0} fases → {1} pétalos','{0} livelli → {1} petali','{0} fases → {1} pétalas','{0} этапов → {1} лепестков'])).items():ROWS[lang].append(text)
KEYS.append('gardenReward')
for lang,text in dict(zip(ROWS,[
'Seeds +{0} · Garden tended','種子 +{0} · 已照料庭院','种子 +{0} · 已照料庭院','種+{0} · 庭のお世話完了','씨앗 +{0} · 정원 돌보기 완료','Samen +{0} · Garten gepflegt','Graines +{0} · Jardin entretenu','Semillas +{0} · Jardín cuidado','Semi +{0} · Giardino curato','Sementes +{0} · Jardim cuidado','Семена +{0} · Сад ухожен'])).items():ROWS[lang].append(text)
if __name__=='__main__':
 p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_bytes().decode();old=next(x for x in s.splitlines() if x.startswith('const L10N='));d=json.loads(old[11:-1]);assert set(d)==set(ROWS)
 for lang,row in ROWS.items():
  assert len(row)==len(KEYS),(lang,len(row));d[lang].update(zip(KEYS,row))
 p.write_bytes(s.replace(old,'const L10N='+json.dumps(d,ensure_ascii=False)+';').encode())
