"""Timed gardening, all eleven locales. Run to update the single-file dictionary."""
import json
from pathlib import Path
KEYS='gardenGrowing gardenHelp gardenCropInfo gardenBatchInfo gardenGrowInfo gardenPlantHarvest gardenReward'.split()
DATA={
'en':['Harvest in {0}','One seed per plant. Crops grow while you are away and never wither. Harvest returns one seed. Clear stages to earn extra seeds. Cottage upgrades unlock plants and scenery, not combat power.','Ready in {0} → {1} petals','Use {0} seeds. Harvest {2} petals in {1}.','Next harvest in {0}. The planting task stays active until you collect it. You may leave; crops keep growing.','Plant & harvest','Seeds +{0}'],
'zh-Hant':['距離收成 {0}','每株花費一顆種子。離線也會成長，成熟後不會枯萎；收成歸還種子。通關可獲得額外種子。小屋升級解鎖植物與景觀，不增加戰鬥能力。','{0} 後成熟 → {1} 片花瓣','花費 {0} 顆種子，{1} 後可收成 {2} 片花瓣。','距離下一次收成 {0}。領取收成後才完成種植任務；可以先離開，作物會繼續成長。','種植與收成','種子 +{0}'],
'zh-Hans':['距离收获 {0}','每株花费一颗种子。离线也会成长，成熟后不会枯萎；收获归还种子。通关可获得额外种子。小屋升级解锁植物与景观，不增加战斗能力。','{0} 后成熟 → {1} 片花瓣','花费 {0} 颗种子，{1} 后可收获 {2} 片花瓣。','距离下次收获 {0}。领取收获后才完成种植任务；可以先离开，作物会继续成长。','种植与收获','种子 +{0}'],
'ja':['収穫まで {0}','植物1株につき種1個。オフラインでも育ち、枯れません。収穫すると種が戻ります。ステージクリアで種を追加獲得。家の修復で植物や景色が増えますが、戦闘能力は変わりません。','{0}後に収穫 → 花びら{1}枚','種{0}個で、{1}後に花びら{2}枚を収穫。','次の収穫まで{0}。収穫するまで栽培タスクは続きます。離れても植物は育ちます。','植えて収穫','種 +{0}'],
'ko':['수확까지 {0}','식물 한 그루에 씨앗 하나가 필요해요. 오프라인에서도 자라며 시들지 않아요. 수확하면 씨앗을 돌려받고, 스테이지를 깨면 추가 씨앗을 얻어요. 집 복원은 식물과 풍경을 열며 전투 능력은 올리지 않아요.','{0} 후 수확 → 꽃잎 {1}개','씨앗 {0}개 사용. {1} 후 꽃잎 {2}개 수확.','다음 수확까지 {0}. 수확해야 재배 임무가 완료돼요. 잠시 떠나도 작물은 계속 자라요.','심고 수확하기','씨앗 +{0}'],
'de':['Ernte in {0}','Ein Samen pro Pflanze. Pflanzen wachsen auch offline und verwelken nie. Bei der Ernte bekommst du den Samen zurück. Levelabschlüsse geben zusätzliche Samen. Der Hausausbau schaltet Pflanzen und Dekoration frei, keine Kampfkraft.','Reif in {0} → {1} Blütenblätter','Verbraucht {0} Samen. In {1} erntest du {2} Blütenblätter.','Nächste Ernte in {0}. Die Pflanzaufgabe endet erst nach dem Einsammeln. Du kannst gehen; die Pflanzen wachsen weiter.','Pflanzen & ernten','Samen +{0}'],
'fr':['Récolte dans {0}','Une graine par plante. Les plantes poussent hors ligne et ne fanent jamais. La récolte rend la graine. Réussir des niveaux rapporte des graines supplémentaires. Rénover débloque des plantes et des décors, pas de puissance de combat.','Prêt dans {0} → {1} pétales','Utilisez {0} graines. Récoltez {2} pétales dans {1}.','Prochaine récolte dans {0}. La tâche se termine après la récolte. Vous pouvez partir : les plantes continuent de pousser.','Planter et récolter','Graines +{0}'],
'es':['Cosecha en {0}','Una semilla por planta. Las plantas crecen sin conexión y nunca se marchitan. La cosecha devuelve la semilla. Superar etapas da semillas extra. Restaurar la casa desbloquea plantas y decoraciones, no poder de combate.','Listo en {0} → {1} pétalos','Usa {0} semillas. Cosecha {2} pétalos en {1}.','Próxima cosecha en {0}. La tarea termina al recogerla. Puedes salir; las plantas siguen creciendo.','Plantar y cosechar','Semillas +{0}'],
'it':['Raccolto tra {0}','Un seme per pianta. Le piante crescono offline e non appassiscono. Il raccolto restituisce il seme. Superare livelli dà semi extra. Il restauro sblocca piante e decorazioni, non potenza di combattimento.','Pronto tra {0} → {1} petali','Usa {0} semi. Raccogli {2} petali tra {1}.','Prossimo raccolto tra {0}. Il compito termina solo dopo la raccolta. Puoi uscire: le piante continuano a crescere.','Piantare e raccogliere','Semi +{0}'],
'pt-BR':['Colheita em {0}','Uma semente por planta. As plantas crescem offline e nunca murcham. A colheita devolve a semente. Concluir fases dá sementes extras. Restaurar a casa libera plantas e cenários, não poder de combate.','Pronto em {0} → {1} pétalas','Usa {0} sementes. Colha {2} pétalas em {1}.','Próxima colheita em {0}. A tarefa só termina após colher. Pode sair: as plantas continuam crescendo.','Plantar e colher','Sementes +{0}'],
'ru':['До урожая {0}','Одно семя на растение. Растения растут без интернета и не вянут. При сборе семя возвращается. Прохождение этапов даёт дополнительные семена. Улучшение дома открывает растения и декорации, но не усиливает в бою.','Созреет через {0} → {1} лепестков','Нужно семян: {0}. Через {1} соберите лепестки: {2}.','До следующего урожая {0}. Задание завершается после сбора. Можно уйти: растения продолжат расти.','Посадить и собрать','Семена +{0}']}
if __name__=='__main__':
 p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_text(encoding='utf-8');old=next(x for x in s.splitlines() if x.startswith('const L10N='));d=json.loads(old[11:-1]);assert set(d)==set(DATA)
 for lang,row in DATA.items():
  assert len(row)==len(KEYS),(lang,len(row));d[lang].update(zip(KEYS,row))
 p.write_text(s.replace(old,'const L10N='+json.dumps(d,ensure_ascii=False)+';'),encoding='utf-8')
