"""Garden layout puzzles and visitors, all eleven locales."""
import json
from pathlib import Path
KEYS='gardenDesignTitle gardenResidents gardenEditHint gardenItem0 gardenItem1 gardenItem2 gardenItem3 gardenItem4 gardenItem5 gardenTile gardenVisitor gardenWish0 gardenWish1 gardenWish2 gardenWish3 gardenWish4 gardenWish5 gardenWelcomed gardenVisitLocked gardenWishReady gardenWishWorking gardenWelcome gardenDesignHelp gardenHint'.split()
DATA={
'en':'''Your little sanctuary|Residents {0}/6|Choose a decoration, then tap a square. Rearrange freely.|Remove|Mint|Flowers|Pond|Bench|Lantern|Row {0}, column {1}: {2}|Visitor {0}|A picnic corner: put a bench beside at least two flower beds.|A cool retreat: put a pond beside at least two mint plants.|A night walk: connect all four lanterns into one path.|Room for friends: give both benches at least two neighbouring flower beds.|A quiet courtyard: mint in all four corners and a pond in one of the four central squares.|A gathering place: use all five decoration types and connect every occupied square.|Moved in!|Clear Stage {0} to meet this visitor.|The garden is ready for this visitor!|Keep arranging — the wish is not fulfilled yet.|Welcome home|Neighbours share an edge, not a corner. Moving decorations is free. Completed wishes stay complete and residents stay home. Decorating grants no combat power.|Build a home worth returning to. Arrange a garden, welcome visitors and grow plants between adventures.''',
'zh-Hant':'''我的小小避風港|居民 {0}/6|選擇擺飾，再點一格放置。可自由重排。|移除|薄荷|花叢|池塘|長椅|提燈|第 {0} 排，第 {1} 格：{2}|訪客 {0}|野餐角落：讓一張長椅與至少兩叢花相鄰。|清涼歇腳處：讓一座池塘與至少兩株薄荷相鄰。|夜間散步：把四盞提燈連成一條相通的小徑。|朋友的座位：讓兩張長椅各自與至少兩叢花相鄰。|寧靜中庭：四個角落都放薄荷，中央四格其中一格放池塘。|相聚的花園：使用全部五種擺飾，並讓所有有擺飾的格子相連。|已入住！|通過第 {0} 關，遇見這位訪客。|庭院已符合這位訪客的願望！|繼續佈置，願望還未完成。|歡迎入住|相鄰是共用一條邊，不含斜角。移動擺飾免費，完成的願望不會倒退，居民也不會離開。佈置不增加戰鬥能力。|打造值得回家的地方。在冒險之間佈置花園、迎接居民，也種出自己的植物。''',
'zh-Hans':'''我的小小避风港|居民 {0}/6|选择摆饰，再点一格放置。可自由重排。|移除|薄荷|花丛|池塘|长椅|提灯|第 {0} 排，第 {1} 格：{2}|访客 {0}|野餐角落：让一张长椅与至少两丛花相邻。|清凉歇脚处：让一座池塘与至少两株薄荷相邻。|夜间散步：把四盏提灯连成一条相通的小径。|朋友的座位：让两张长椅各自与至少两丛花相邻。|宁静中庭：四个角落都放薄荷，中央四格其中一格放池塘。|相聚的花园：使用全部五种摆饰，并让所有有摆饰的格子相连。|已入住！|通过第 {0} 关，遇见这位访客。|庭院已符合这位访客的愿望！|继续布置，愿望还未完成。|欢迎入住|相邻是共用一条边，不含斜角。移动摆饰免费，完成的愿望不会倒退，居民也不会离开。布置不增加战斗能力。|打造值得回家的地方。在冒险之间布置花园、迎接居民，也种出自己的植物。''',
'ja':'''小さな憩いの場所|住人 {0}/6|飾りを選び、マスをタップ。何度でも並べ替えられます。|取り除く|ミント|花|池|ベンチ|ランタン|{0}行、{1}列：{2}|訪問者 {0}|ピクニックの場所：ベンチ1つに花を2つ以上隣接させよう。|涼しい休憩所：池1つにミントを2つ以上隣接させよう。|夜の散歩：4つのランタンをひと続きの道にしよう。|友達の席：2つのベンチそれぞれに花を2つ以上隣接させよう。|静かな中庭：四隅にミント、中央4マスのどこかに池を置こう。|集いの庭：5種類すべての飾りを使い、飾りのあるマスをすべてつなごう。|入居しました！|ステージ{0}をクリアすると出会えます。|この訪問者を迎える準備ができました！|願いはまだ叶っていません。並べ方を工夫しよう。|ようこそ！|隣接は辺でつながること。斜めは含みません。移動は無料。達成した願いは取り消されず、住人も残ります。戦闘能力は増えません。|帰りたくなる場所を作ろう。冒険の合間に庭を飾り、住人を迎え、植物を育てよう。''',
'ko':'''나만의 작은 쉼터|주민 {0}/6|장식을 고른 뒤 칸을 누르세요. 자유롭게 다시 배치할 수 있어요.|치우기|민트|꽃|연못|벤치|등불|{0}행 {1}열: {2}|방문객 {0}|소풍 자리: 벤치 하나에 꽃밭 두 개 이상이 이웃하게 놓으세요.|시원한 쉼터: 연못 하나에 민트 두 개 이상이 이웃하게 놓으세요.|밤 산책: 등불 네 개를 하나의 길로 연결하세요.|친구들의 자리: 벤치 두 개 각각에 꽃밭 두 개 이상이 이웃하게 놓으세요.|고요한 안뜰: 네 모서리에 민트를, 가운데 네 칸 중 한 곳에 연못을 놓으세요.|함께하는 정원: 다섯 종류 장식을 모두 사용하고 장식이 있는 모든 칸을 연결하세요.|입주 완료!|스테이지 {0}을 완료하면 만날 수 있어요.|방문객의 소원에 맞는 정원이 완성됐어요!|아직 소원을 이루지 못했어요. 배치를 바꿔 보세요.|입주 환영|이웃한 칸은 변을 공유하며 대각선은 제외됩니다. 이동은 무료예요. 완료한 소원은 유지되고 주민도 떠나지 않아요. 전투 능력은 늘어나지 않아요.|돌아오고 싶은 집을 만드세요. 모험 사이에 정원을 꾸미고 주민을 맞이하며 식물을 키우세요.''',
'de':'''Dein kleiner Rückzugsort|Bewohner {0}/6|Wähle eine Deko und tippe auf ein Feld. Umstellen ist kostenlos.|Entfernen|Minze|Blumen|Teich|Bank|Laterne|Zeile {0}, Spalte {1}: {2}|Besucher {0}|Picknickplatz: Eine Bank soll an mindestens zwei Blumenbeete grenzen.|Kühler Rückzugsort: Ein Teich soll an mindestens zwei Minzpflanzen grenzen.|Nachtspaziergang: Verbinde alle vier Laternen zu einem Weg.|Platz für Freunde: Beide Bänke sollen jeweils an mindestens zwei Blumenbeete grenzen.|Ruhiger Hof: Minze in alle vier Ecken und ein Teich auf eines der vier mittleren Felder.|Treffpunkt: Nutze alle fünf Dekoarten und verbinde alle belegten Felder.|Eingezogen!|Schaffe Stufe {0}, um diesen Besucher zu treffen.|Der Garten ist für diesen Besucher bereit!|Der Wunsch ist noch nicht erfüllt. Probiere eine andere Anordnung.|Willkommen zu Hause|Benachbarte Felder teilen eine Kante, keine Ecke. Umstellen ist kostenlos. Erfüllte Wünsche bleiben erfüllt und Bewohner bleiben. Deko erhöht keine Kampfwerte.|Baue ein Zuhause, in das du gern zurückkehrst. Gestalte den Garten, begrüße Besucher und ziehe Pflanzen zwischen Abenteuern.''',
'fr':'''Votre petit refuge|Résidents {0}/6|Choisissez un décor, puis touchez une case. Déplacez-le librement.|Retirer|Menthe|Fleurs|Bassin|Banc|Lanterne|Ligne {0}, colonne {1} : {2}|Visiteur {0}|Coin pique-nique : placez un banc à côté d’au moins deux massifs de fleurs.|Refuge frais : placez un bassin à côté d’au moins deux plants de menthe.|Balade nocturne : reliez les quatre lanternes en un seul chemin.|Entre amis : chacun des deux bancs doit toucher au moins deux massifs de fleurs.|Cour paisible : de la menthe aux quatre coins et un bassin sur l’une des quatre cases centrales.|Lieu de rencontre : utilisez les cinq types de décors et reliez toutes les cases occupées.|Installé !|Réussissez le niveau {0} pour rencontrer ce visiteur.|Le jardin est prêt pour ce visiteur !|Le souhait n’est pas encore réalisé. Essayez un autre agencement.|Bienvenue chez vous|Les voisins partagent un côté, pas un coin. Déplacer les décors est gratuit. Les souhaits réalisés le restent et les résidents restent chez eux. Aucun bonus de combat.|Créez un lieu où il fait bon revenir. Aménagez le jardin, accueillez des visiteurs et cultivez des plantes entre les aventures.''',
'es':'''Tu pequeño refugio|Residentes {0}/6|Elige un adorno y toca una casilla. Puedes reorganizar gratis.|Quitar|Menta|Flores|Estanque|Banco|Farol|Fila {0}, columna {1}: {2}|Visitante {0}|Rincón de pícnic: coloca un banco junto a al menos dos parterres.|Refugio fresco: coloca un estanque junto a al menos dos plantas de menta.|Paseo nocturno: conecta los cuatro faroles en un solo camino.|Sitio para amigos: cada uno de los dos bancos debe tocar al menos dos parterres.|Patio tranquilo: menta en las cuatro esquinas y un estanque en una de las cuatro casillas centrales.|Lugar de reunión: usa los cinco tipos de adornos y conecta todas las casillas ocupadas.|¡Ya se ha mudado!|Supera la fase {0} para conocer a este visitante.|¡El jardín está listo para este visitante!|El deseo aún no se ha cumplido. Prueba otra distribución.|Bienvenido a casa|Las casillas vecinas comparten un lado, no una esquina. Mover adornos es gratis. Los deseos cumplidos se conservan y los residentes se quedan. No aumenta el poder de combate.|Crea un hogar al que quieras volver. Decora el jardín, recibe visitantes y cultiva plantas entre aventuras.''',
'it':'''Il tuo piccolo rifugio|Abitanti {0}/6|Scegli una decorazione e tocca una casella. Spostala liberamente.|Rimuovi|Menta|Fiori|Stagno|Panchina|Lanterna|Riga {0}, colonna {1}: {2}|Visitatore {0}|Angolo picnic: metti una panchina accanto ad almeno due aiuole.|Rifugio fresco: metti uno stagno accanto ad almeno due piante di menta.|Passeggiata notturna: collega tutte e quattro le lanterne in un unico sentiero.|Posto per gli amici: entrambe le panchine devono avere almeno due aiuole adiacenti.|Cortile tranquillo: menta ai quattro angoli e uno stagno in una delle quattro caselle centrali.|Luogo d’incontro: usa tutti e cinque i tipi di decorazione e collega tutte le caselle occupate.|Si è trasferito!|Supera il livello {0} per incontrare questo visitatore.|Il giardino è pronto per questo visitatore!|Il desiderio non è ancora esaudito. Prova un’altra disposizione.|Benvenuto a casa|Le caselle vicine condividono un lato, non un angolo. Spostare è gratis. I desideri esauditi restano tali e gli abitanti rimangono. Nessun bonus in battaglia.|Crea una casa in cui tornare volentieri. Decora il giardino, accogli visitatori e coltiva piante tra un’avventura e l’altra.''',
'pt-BR':'''Seu pequeno refúgio|Moradores {0}/6|Escolha uma decoração e toque numa casa. Reorganize de graça.|Remover|Hortelã|Flores|Lago|Banco|Lanterna|Linha {0}, coluna {1}: {2}|Visitante {0}|Cantinho de piquenique: coloque um banco junto de pelo menos dois canteiros de flores.|Refúgio fresco: coloque um lago junto de pelo menos duas plantas de hortelã.|Passeio noturno: conecte as quatro lanternas num único caminho.|Lugar para amigos: cada um dos dois bancos deve tocar pelo menos dois canteiros de flores.|Pátio tranquilo: hortelã nos quatro cantos e um lago numa das quatro casas centrais.|Ponto de encontro: use os cinco tipos de decoração e conecte todas as casas ocupadas.|Já se mudou!|Vença a fase {0} para conhecer este visitante.|O jardim está pronto para este visitante!|O desejo ainda não foi realizado. Tente outra disposição.|Boas-vindas ao lar|Casas vizinhas compartilham um lado, não um canto. Mover é grátis. Desejos realizados continuam completos e moradores ficam. Não aumenta o poder de combate.|Crie um lar ao qual queira voltar. Decore o jardim, receba visitantes e cultive plantas entre aventuras.''',
'ru':'''Ваш маленький уголок|Жители {0}/6|Выберите украшение и нажмите на клетку. Перестановка бесплатна.|Убрать|Мята|Цветы|Пруд|Скамья|Фонарь|Ряд {0}, столбец {1}: {2}|Гость {0}|Место для пикника: рядом со скамьёй должны быть хотя бы два цветника.|Прохладный уголок: рядом с прудом должны быть хотя бы два куста мяты.|Ночная прогулка: соедините все четыре фонаря в одну дорожку.|Место для друзей: рядом с каждой из двух скамеек должны быть хотя бы два цветника.|Тихий двор: мята во всех четырёх углах и пруд в одной из четырёх центральных клеток.|Место встречи: используйте все пять видов украшений и соедините все занятые клетки.|Уже живёт здесь!|Пройдите этап {0}, чтобы встретить этого гостя.|Сад готов принять этого гостя!|Желание ещё не исполнено. Попробуйте другую расстановку.|Добро пожаловать|Соседние клетки имеют общую сторону, а не угол. Перестановка бесплатна. Исполненные желания сохраняются, жители остаются. Боевые характеристики не растут.|Создайте дом, куда хочется возвращаться. Украшайте сад, встречайте гостей и выращивайте растения между приключениями.'''
}
if __name__=='__main__':
 p=Path(__file__).resolve().parents[1]/'index.html';s=p.read_text(encoding='utf-8');old=next(x for x in s.splitlines() if x.startswith('const L10N='));d=json.loads(old[11:-1]);assert set(d)==set(DATA)
 for lang,text in DATA.items():
  row=text.split('|');assert len(row)==len(KEYS),(lang,len(row),len(KEYS));d[lang].update(zip(KEYS,row))
 p.write_text(s.replace(old,'const L10N='+json.dumps(d,ensure_ascii=False)+';'),encoding='utf-8')
